### ISSUE TITLE
Nicer, Persistent URIs

### ISSUE THREAD

**Issue by jpstroop** [pulibrary/pomegranate#103]
Can we reuse Plum's NOID? instead of UUIDs? There's enough context in the URI that we won't run into trouble if an object is in more than one collection:

`/east_asian/catalog/151376964b0348f81308a7be81d8c739`

Also, could imagine a service that answers "show me the collections this item is in" for creating links from Orangelight out the the item's other viewing contexts.

**Comment by tpendragon** [comment]
The UUIDs are actually contextual IDs - there's a solr record per item per collection in Pom. https://github.com/sul-dlss/spotlight-resources-iiif/blob/master/app/models/spotlight/resources/iiif_manifest.rb#L30

**Comment by tpendragon** [comment]
What we might be able to do is setup the route to do the conversion to the compound ID, but Blacklight might get upset.

**Comment by escowles** [comment]
We could override the `IiifManifest#compound_id` method to customize the spotlight id.  We could extract the pid from the url that we already have to make the id something like `#{exhibit.id}-#{pid}`

**Comment by jpstroop** [comment]
`/slug/plum_noid` would be ideal.
