### ISSUE TITLE
Fix text padding/line spacing

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/pomegranate#1129]
Staging:

![Screen Shot 2021-10-14 at 12.54.01 PM.png](https://images.zenhubusercontent.com/5c8fd280aa8dca0a81398108/07e21de2-760c-411d-8e02-50df39212378)

Production:

![Screen Shot 2021-10-14 at 12.54.12 PM.png](https://images.zenhubusercontent.com/5c8fd280aa8dca0a81398108/eb55e8b5-e3e3-4ae0-9d5e-2bcb1fa03f7d)

URL: https://dpul.princeton.edu/piranesi/feature/a-maker-of-books

This might be a font size thing too?

**Comment by kelea99** [comment]
@sdellis can  you weigh in here?  what do you think about the spacing and usability? the font size also looks larger in staging.
