### ISSUE TITLE
Spanish labels are displaying for page navbar even when set to english

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/pomegranate#1136]
![Screen Shot 2021-10-15 at 9.20.50 AM.png](https://images.zenhubusercontent.com/5c8fd280aa8dca0a81398108/3c29d031-8d86-43d0-a2a9-91eef4ee2373)

https://dpul-staging.princeton.edu/chilean_photographs

**Comment by kelea99** [comment]
Yes, we still have this issue: https://dpul-staging.princeton.edu/chilean_photographs/home?locale=es
