### ISSUE TITLE
Blocks Release: Facets are displaying a border above them which looks bad.

### ISSUE THREAD

**Issue by kelea99** [pulibrary/pomegranate#1158]
@sdellis I want to say this blocks release, but would like weigh in from you and other folks before moving forward.  
![Screen Shot 2021-10-20 at 12 47 29 PM](https://user-images.githubusercontent.com/45043014/138136330-4c8720a3-8903-4713-8098-474e359d583b.png)

**Comment by kelea99** [comment]
confirmed:  blocks releasse

**Comment by tpendragon** [comment]
The problem here is that there's a border that's above the facet that looks bad.
