### ISSUE TITLE
Blocks Release: CSS for faceted search results needs work

### ISSUE THREAD

**Issue by kelea99** [pulibrary/pomegranate#1164]
There are a couple of things going on here. I can break out separate tickets if preferred, but the screenshot below shows:
1. green color for search results in faceting. Im not exactly against it but it is a bit unexpected and jarring. @sdellis any suggestions on what would/could work here?
2. Button for what was searched for (to the right of the blue "start over" button)
<img width="1440" alt="Screen Shot 2021-10-21 at 4 20 46 AM" src="https://user-images.githubusercontent.com/45043014/138240522-6869f68b-501e-4b0e-97e5-e8f763e63e6a.png">

**Comment by sdellis** [comment]
Take the green color off the header, but use prod green on text.
