### ISSUE TITLE
Add ability to remove iiif items

### ISSUE THREAD

**Issue by eliotjordan** [pulibrary/pomegranate#124]
Add the ability to remove iiif items from a collection. Unless I'm missing it somewhere, I don't see any functionality in Spotlight to do this.

**Comment by tpendragon** [comment]
Collection management is handled in Plum - this was actually something we removed from Spotlight.

**Comment by eliotjordan** [comment]
Exhibit == Collection, yes? What if a curator wants to put together an exhibit that incorporates items from outside sources. Is that out of scope for Pom? And if so, are we planning to offer other spotlight instances that are more flexible?

**Comment by escowles** [comment]
Yes, right now the scope of Pom is Plum collections.  We haven't talked about incorporating external resources, though that seems like a good thing to bring up.
