### ISSUE TITLE
Split subjects into individual topics

### ISSUE THREAD

**Issue by jpstroop** [pulibrary/pomegranate#132]
Rather than long precoordinated strings

![image](https://cloud.githubusercontent.com/assets/999701/20320325/864b345e-ab3f-11e6-8f4e-91640d6f5b4d.png)

**Comment by tpendragon** [comment]
This is similar to the Subject: Topic/Subject: Era/Subject: Genre facets in the Catalog: https://catalog.princeton.edu/catalog?utf8=%E2%9C%93&search_field=all_fields&q=

**Comment by hackmastera** [comment]
This would replicate behavior of the catalog. We're not sure if we have this use case.
