### ISSUE TITLE
Add Digital PUL Logo

### ISSUE THREAD

**Issue by jpstroop** [pulibrary/pomegranate#135]
@marvinmarvinb agrees, let's not form a committee. :wink:

**Comment by jpstroop** [comment]
I guess we would alias as `dpul` then too.

**Comment by tpendragon** [comment]
This is configurable for the title. It's been done - @jpstroop do you want a new ticket for a logo, or just rename this one?

**Comment by jpstroop** [comment]
See #172 and #156
