### ISSUE TITLE
Arabic Titles need to show in list

### ISSUE THREAD

**Issue by jpstroop** [pulibrary/pomegranate#138]
Title is switched on, but not showing:
![image](https://cloud.githubusercontent.com/assets/999701/20408306/ec6c9260-ace2-11e6-9538-24e9de6034e4.png)

**Comment by tpendragon** [comment]
Do any of those have arabic titles in plum?

**Comment by jpstroop** [comment]
Hmm..doesn't look like it, but they should!

Doesn't look like they're in the manifest either.

https://pulsearch.princeton.edu/catalog/7849192
http://plum.princeton.edu/concern/scanned_resources/pdr26zb47k

**Comment by jpstroop** [comment]
Cf. pulibrary/plum#833
