### ISSUE TITLE
metadata spacing on show view needs help

### ISSUE THREAD

**Issue by jpstroop** [pulibrary/pomegranate#140]
![image](https://cloud.githubusercontent.com/assets/999701/20408526/e3d6c7e6-ace3-11e6-8c69-35e2fd3d5838.png)

Also, like #138, I can't figure our how to get Arabic to show up.

**Comment by tpendragon** [comment]
Are you referring to the spacing between the viewer and the metadata?

**Comment by jpstroop** [comment]
yeah, and the metadata is in a narrow column rather than spanning the width (more or less) of the creen.

**Comment by tpendragon** [comment]
:+1:
