### ISSUE TITLE
Need something on the homepage

### ISSUE THREAD

**Issue by jpstroop** [pulibrary/pomegranate#143]
Marvin would still like search across, but at the very least we should see all collections

![image](https://cloud.githubusercontent.com/assets/999701/20411525/df358720-acef-11e6-80a0-5595d5eae3a7.png)

**Comment by jpstroop** [comment]
also, can we get `/spotlight/` out of the routes?

**Comment by tpendragon** [comment]
The published collections show up on the homepage when they're published.

**Comment by tpendragon** [comment]
Also, there's search across. That's what the search bar does.

**Comment by tpendragon** [comment]
Removing `spotlight` from the routes may be tough. We can change it, but I don't think it can be at the root (blacklight's mounted there.)
