### ISSUE TITLE
Pomegranate should embed a high resolution version of the thumbnail for slideshows.

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/pomegranate#147]
So if I choose an image to display first, that should be the image that shows up in the embed.

**Comment by jpstroop** [comment]
I'd rather this be the thumbnail from the manifest if possible; first image is often boring.

**Comment by tpendragon** [comment]
The resolution will be too low, unless we start building up IIIF paths to figure out the image. IIIF doesn't have a "full res interesting image" spot does it?

**Comment by jpstroop** [comment]
Hmm. Could we make our thumbnail a service instead?

**Comment by jpstroop** [comment]
http://iiif.io/api/presentation/2.1/#thumbnail

**Comment by tpendragon** [comment]
I think it's already a service: http://lib-plum1.princeton.edu/concern/scanned_resources/pvt150q36n/manifest. So we just take the service ID and append the appropriate params to resize?

**Comment by jpstroop** [comment]
So it is! Yup.

**Comment by tpendragon** [comment]
Updated the title - sound accurate?
