### ISSUE TITLE
Selected thumbnail and image in slideshow do not correspond

### ISSUE THREAD

**Issue by jpstroop** [pulibrary/pomegranate#158]
E.g. I chose:

![image](https://cloud.githubusercontent.com/assets/999701/20970147/29e18a0c-bc5a-11e6-8911-5b930c0bfedc.png)

but when I go to look at the page I see:

![image](https://cloud.githubusercontent.com/assets/999701/20970181/4f0c5e88-bc5a-11e6-8268-cfb7ff5549d0.png)

For the second image. Could it be that one is using the IIIF thumbnail and the other is using the first image?

**Comment by tpendragon** [comment]
Yes, that's why. I think this is a duplicate of https://github.com/pulibrary/pomegranate/issues/147

**Comment by jpstroop** [comment]
yup
