### ISSUE TITLE
Date display should be as-is from MARC 260

### ISSUE THREAD

**Issue by jpstroop** [pulibrary/pomegranate#178]
E.g. in Mesoamerican, _Ritual of the bacabs_, Date is "1775-1800", but in the MARC 260 it's "[between 1775 and 1800]"

Also, closely related, the date is wrong in the manifest:

![image](https://cloud.githubusercontent.com/assets/999701/21652982/039e1516-d27d-11e6-82df-9ef5e11b383d.png)

**Comment by tpendragon** [comment]
Looks like this is a case of it not being in the JSON-LD.
