### ISSUE TITLE
In Curation > Items > Edit, don't display fields that can't be edited

### ISSUE THREAD

**Issue by jpstroop** [pulibrary/pomegranate#179]
For some reason I thought @tpendragon already did this?

**Comment by tpendragon** [comment]
They're displayed and marked as readonly so you know what kind of fields you already have on the item, and can easily copy imported fields.

**Comment by tpendragon** [comment]
@jpstroop Do you still want this to happen given the above?

**Comment by jpstroop** [comment]
This was a nice-to-have from @joycebcat, but I see what you're saying. Joyce, what do you think?

**Comment by joycebcat** [comment]
@tpendragon This was something I commented on.  It isn't terribly important but when Jon and I were going over it I thought that curators would be struck by selecting "edit" and then not seeing anything that could actually be edited.  The only part which can be changed is way at the bottom.  You could completely table this until/unless curators actually comment on it.
