### ISSUE TITLE
How to change fields that appear in search results when searching across all collections?

### ISSUE THREAD

**Issue by jpstroop** [pulibrary/pomegranate#197]

**Comment by tpendragon** [comment]
There was a discussion about this when the feature was added - these have to be added in code when we know which fields to show.

**Comment by jpstroop** [comment]
OK. This and also facets.

PUDL uses:Title, Creator, the Publication Statement, and the Collection to which it belongs. Collection_s_ in this case. Does that seem feasible?

For facets, how about Collection, Language, Subject to start? I'm not sure the jsonld has everything we need (e.g. Type would be nice)

**Comment by tpendragon** [comment]
So, "collection" is actually hard to do. There's a solr document per collection, and they're de-duplicated (no such thing as a SQL-like join in Solr). Every indexed collection document would need to know which collections it's a member of, and more importantly which of those are currently in pomegranate. It's not impossible, but it's not something we maintain right now (you'd have to update solr records when you index an object which is in another collection that pom has.)

**Comment by jpstroop** [comment]
Yup, OK. Let's put that in a separate ticket for later and do the rest?
