### ISSUE TITLE
Display problems w/ slideshow

### ISSUE THREAD

**Issue by jpstroop** [pulibrary/pomegranate#224]
![screen shot 2017-02-07 at 8 31 32 am](https://cloud.githubusercontent.com/assets/999701/22693101/eaae872c-ed0f-11e6-822d-71f0d0282eea.png)

**Comment by tpendragon** [comment]
Which record is that? Guessing this is just a case of a quotation mark not getting escaped

**Comment by jpstroop** [comment]
Shoot, forgot the URL. I'll try to get it tomorrow.

-Js

Sent via mobile. Please excuse typos, brevity, etc.

On Feb 7, 2017 12:25 PM, "Trey Pendragon" <notifications@github.com> wrote:

Which record is that? Guessing this is just a case of a quotation mark not
getting escaped

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/pulibrary/pomegranate/issues/224#issuecomment-278073434>,
or mute the thread

**Comment by jpstroop** [comment]
That's a good guess, anyway. Here's that record:

https://dpul.princeton.edu/spotlight/pudl0127/catalog/d0586fbf8d62b5bb8c0daf990f77cb87

This might also be related:

https://dpul.princeton.edu/spotlight/pudl0127/catalog/4136399ea9b7c73c33a83a37c7f60f60

In this case there is a `&#39;` in the "Description" field. So there are escaping issues both ways.

And characters that can't be rendered by UV as well. I think we have a ticket for that already though

**Comment by tpendragon** [comment]
This is still a problem.
