### ISSUE TITLE
Strings are improperly escaped in catalog display.

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/pomegranate#245]
https://dpul.princeton.edu/pudl0127/catalog/th83m208g for example shows `[Moskva ; Leningrad] : &quot;Raduga,&quot; 1926.`

**Comment by tampakis** [comment]
Yay no longer an issue! https://dpul.princeton.edu/slavic/catalog?utf8=%E2%9C%93&exhibit_id=slavic&search_field=all_fields&q=Znakomye+neznakomt%EF%B8%A0s%EF%B8%A1y
