### ISSUE TITLE
Remove fields from default display

### ISSUE THREAD

**Issue by jpstroop** [pulibrary/pomegranate#246]
From this page: https://dpul.princeton.edu/pudl0127/catalog/th83m208

Title sort, Created, Edm rights, Collections, Identfier should not display. Author and Creator are redundant. 

I also expect that questions about order will come up.

**Comment by tpendragon** [comment]
@joycebcat When you first create a collection, would you like all the fields to be displayed by default and the curators can hide them, or is there a list you'd like to display?

**Comment by joycebcat** [comment]
@tpendragon I would like some default settings.  I've just been figuring them out from the mapping James did for me Friday.  Things NOT to be checked by default:

range label
created
collection
publisher
title sort
date
references

**Comment by hackmastera** [comment]
It is fine to do this manually.
