### ISSUE TITLE
500 when trying to add a user to an exhibit

### ISSUE THREAD

**Issue by jpstroop** [pulibrary/pomegranate#256]

**Comment by tpendragon** [comment]
https://rpm.newrelic.com/accounts/369675/applications/32329358/traced_errors/2a3fd0e8-0f39-11e7-b3b0-b82a72d22a14_0_27230 This must be what happens when you add someone and they haven't logged in yet.

**Comment by jpstroop** [comment]
I wondered that, but I don't remember Don or Chloe (the last people Joyce did DPUL demos for) having logged in first.

**Comment by tpendragon** [comment]
I'm saying this is what happens if they DON'T log in first.

**Comment by jpstroop** [comment]
Me too--Don and Chloe hadn't logged in before, I don't *think*. I can write to Mark and Sandy and ask them to log in once, if that's the solution.

**Comment by tpendragon** [comment]
We should fix this, but that'll get them in for the moment.
