### ISSUE TITLE
IIIF Drag & Drop

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/pomegranate#262]
e.g., create a drag-and-drop icon:

* https://zimeon.github.io/iiif-dragndrop/
* logo: https://drive.google.com/drive/u/0/folders/0B8APFBow4sHvY044Sm10SFdNWG8

Moved from https://github.com/pulibrary/plum/issues/177

**Comment by escowles** [comment]
Current Stanford implementation:
![screen shot 2018-11-26 at 1 36 07 pm](https://user-images.githubusercontent.com/856924/49034573-58a33900-f180-11e8-93e1-da64da58142c.png)

**Comment by escowles** [comment]
Maybe the icon should be grayscale, less prominent (on show page, not search results).
