### ISSUE TITLE
Ark Resolver: List collections that a given ark is a member of (with links)

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/pomegranate#263]
Use Case: There should be a link from the catalog to the DPUL collections they're a member of.

This was a proposed technical solution, so that AJAX in Orangelight can ask for a set of links for a given ARK. Could also be implemented as GraphQL, now that we have it.

**Comment by eliotjordan** [comment]
Context needed.

**Comment by tpendragon** [comment]
The use case is to allow the catalog to show which DPUL collections an item is in. Still a use case? @tampakis @joycebcat ?

**Comment by hackmastera** [comment]
Closing due to no requests for this feature.
