### ISSUE TITLE
scroll objects spin forever, although you can zoom on them and they will work while not looking like they have loaded yet.

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/pomegranate#265]
Example: https://dpul.princeton.edu/eastasian/catalog/hx11xg54f

**Comment by tpendragon** [comment]
I reported this to UV devs and they say it can't display in OpenSeaDragon either: http://tomcrane.github.io/scratch/osd/single-image.html?image=https://libimages1.princeton.edu/loris/plum_prod%2Fpm%2Fp4%2F8t%2Fj2%2F7g-intermediate_file.jp2/info.json. Maybe a Loris bug?

**Comment by jpstroop** [comment]
I haven't had a chance to look, but have a feeling that this is a Loris bug. I think the extreme aspect ratio of the scroll might be rounding the y-dimension to 0.

**Comment by tpendragon** [comment]
Confirmed this is loris. Works with Cantaloupe.

**Comment by tpendragon** [comment]
Just a note, I don't think that's a good test. That record's pulling from production figgy, and the images are coming from Loris: `https://libimages1.princeton.edu/loris/figgy_prod%2Fec%2Fb7%2Fa4%2Fecb7a49b79804d42a98ee93a42d3f3dd%2Fintermediate_file.jp2/full/200,/0/default.jpg`

**Comment by hackmastera** [comment]
These appear to be working.

**Comment by hackmastera** [comment]
updated example link: https://dpul.princeton.edu//catalog/9g54xn18w#?c=0&m=0&s=0&cv=0&xywh=0%2C-4491%2C51060%2C12580
