### ISSUE TITLE
uploading external image

### ISSUE THREAD

**Issue by joycebcat** [pulibrary/pomegranate#269]
Chloe in RB reports that when she tried to upload an image from outside DPUL, she got a page telling her she was not authorized to access the page.  (She is able to use images from within the system)

**Comment by eliotjordan** [comment]
Need more context here. Is this still valid?

**Comment by joycebcat** [comment]
I believe so, yes.  I don't get the unauthorized message, but images that I tried to upload as recently as last week didn't appear in the system.

**Comment by escowles** [comment]
@joycebcat Is this different from #271 ?

**Comment by joycebcat** [comment]
@escowles No, I believe this is the same problem was #271.  Sorry for the duplication.

**Comment by escowles** [comment]
@joycebcat No worries, we do it all the time!
