### ISSUE TITLE
Collection admins are unable to upload their own photos for About page

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/pomegranate#271]

**Comment by eliotjordan** [comment]
Still broken?

**Comment by hackmastera** [comment]
could be a permissions issue similar to https://github.com/projectblacklight/spotlight/issues/1752?

**Comment by jrgriffiniii** [comment]
I'm also experiencing difficulties rendering uploaded custom images to the site masthead

**Comment by jrgriffiniii** [comment]
The images are being successfully uploaded to https://github.com/projectblacklight/spotlight/blob/0ff14576f8748bf529b23728287ebb404dff74c8/app/uploaders/spotlight/featured_image_uploader.rb#L12

**Comment by jrgriffiniii** [comment]
Within `PagesController`, the parameters for a newly-uploaded thumbnail don't seem to contain values for a valid IIIF Manifest:
```ruby
pry(#<Spotlight::HomePagesController>)> page_params['thumbnail_attributes']
<ActionController::Parameters {"source"=>"remote", "document_global_id"=>"", "iiif_region"=>"103,1,205,153", "iiif_tilesource"=>"http://localhost:3000/images/16/info.json", "iiif_manifest_url"=>"", "iiif_canvas_id"=>"", "iiif_image_id"=>""} permitted: true>
```
