### ISSUE TITLE
Add a banner note about IE not working

### ISSUE THREAD

**Issue by joycebcat** [pulibrary/pomegranate#282]
One of the people I met with this week asked if we could add a note to the "beta" banner on DPUL noting that it doesn't work with IE.  I think this would be a really good idea and timely since the volume is increasing and we are starting to put material there which doesn't appear in the old system.

**Comment by tpendragon** [comment]
@joycebcat Was the only IE issue the card flipping? Because we fixed that yesterday.

**Comment by joycebcat** [comment]
@tpendragon Oh, hey!  Great.  It works in IE now.  Never mind, I'm closing the ticket.
