### ISSUE TITLE
MVWs marked as taken down in Plum aren't being marked private in DPUL

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/pomegranate#284]

**Comment by jrgriffiniii** [comment]
`IIIFResource` does not `save` properly when a 403 response is given for a MVW Manifest which is updated as private: https://github.com/projectblacklight/spotlight/blob/master/app/models/spotlight/resource.rb#L27

**Comment by jrgriffiniii** [comment]
@tpendragon discovered that this has been fully resolved
