### ISSUE TITLE
Make Sanborn exhibit

### ISSUE THREAD

**Issue by jpstroop** [pulibrary/pomegranate#286]
So that we can kill http://libweb5.princeton.edu/visual_materials/maps/sanborn/sanborn-web.htm

**Comment by escowles** [comment]
Should have county facet.

**Comment by tpendragon** [comment]
@eliotjordan I'm going through old tickets. Is this still a thing that needs done?

**Comment by eliotjordan** [comment]
Nah. I think this ticket replaces this one: https://github.com/pulibrary/pulmap/issues/796
