### ISSUE TITLE
Input all of the items from a plum collection

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/pomegranate#3]
Given a collection manifest URL:

* Retrieve the manifest and extract a list of item manifest URLs
* Spawn a worker to index each of those manifests in Spotlight (can be inline for now, but will eventually need to be a background job)

**Comment by escowles** [comment]
With https://github.com/pulibrary/plum/pull/335, we'll be able to easily fetch a list of resource ids from blacklight based on the collection slug.

**Comment by escowles** [comment]
Thinking about how this will work:

1. Go to an exhibit, click a button to ingest items from Plum from the corresponding collection
2. A background job is started that does a search in Plum and extracts the PIDs of the items to ingest
3. Each item's manifest is fetched from Plum and ingested
4. There should also be a background job to ingest a single item, so the collection ingest job should re-use that for ingesting items
