### ISSUE TITLE
Overlay overflow in Firefox

### ISSUE THREAD

**Issue by escowles** [pulibrary/pomegranate#301]
Several users reported an issue with the facet "more" modal being cut off in Firefox.

Screen shot:
![dpul](https://user-images.githubusercontent.com/856924/34785064-0b180194-f5fe-11e7-9dc0-fc1afbd35e74.png)

**Comment by hackmastera** [comment]
To reproduce, scroll down the page a bit before clicking "more". the lightbox seems fixed on the "above the fold" portion of the page even though the page has been scrolled.

**Comment by escowles** [comment]
We should test this in staging, with enough data to demonstrate this issue and test fixes
