### ISSUE TITLE
Full screen doesn't work in DPUL

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/pomegranate#306]
![screen shot 2018-01-24 at 11 35 01 am](https://user-images.githubusercontent.com/2806645/35353007-ad22e7a4-00fa-11e8-9d23-0273fb6015fb.png)

**Comment by hackmastera** [comment]
broken in safari 11.0.3. works in ff 58.0.2 and chrome 64.0.3282.167 (seriously, what kind of version number is that)

**Comment by jrgriffiniii** [comment]
The following errors could be isolated within Safari:
```
[...]/assets/openseadragon/openseadragon.js.map
[...]/universalviewer/dist/uv-1.8.42/lib/openseadragon.min.js.map
```
