### ISSUE TITLE
Fix staging

### ISSUE THREAD

**Issue by escowles** [pulibrary/pomegranate#312]
We should be able to add collections in Staging to test with larger data sets.

**Comment by hackmastera** [comment]
It looks like staging is hooked up to figgy-staging. maybe pointing it at production figgy would fix this?

**Comment by hackmastera** [comment]
The box is missing services for both sneakers and sidekiq. I'd probably just consider this superceded by #313 at this point.

**Comment by hackmastera** [comment]
I pointed it at production figgy. see also relevant pr. this should put is back in business until the new box is ready.

**Comment by hackmastera** [comment]
I started a collection for the "Treasures of the Cotsen Collection" so we'll see if that's enough data.
