### ISSUE TITLE
Document ways to make collection pages visually engaging

### ISSUE THREAD

**Issue by escowles** [pulibrary/pomegranate#315]
Create some documentation for staff users with examples of the different widgets and how they can be used to create image-rich collection descriptions. Include guidelines as to what sort of content should go on the collection "home" page and what sort of content should go on the "about" page.

**Comment by escowles** [comment]
Adding /improving docs in https://drive.google.com/drive/folders/0AJjNdp9TiOrcUk9PVA would be good

**Comment by sdellis** [comment]
I would look at the Google Cultural Institute for inspiration. They focus on telling the stories with large engaging imagery, either in scrolling or "slideshow" narrative form. https://artsandculture.google.com/

**Comment by hackmastera** [comment]
@sdellis this ticket is for documenting how to use functionality we already available to us in spotlight in more effective ways. Do you think google cultural institute can inform us in that context?

**Comment by sdellis** [comment]
@hackmastera When I added that comment, I assumed that we can use functionality in Spotlight, but still change the Spotlight UI. If so, then the Google Cultural Institute is entirely relevant. I can't imagine why this issue was created if we can't change the UI.

**Comment by hackmastera** [comment]
after chatting with @sdellis I added to the description of this issue; hopefully that will clarify!

**Comment by hackmastera** [comment]
So we have a few different types of content on the table here:
- (A) Search results limited to the collection
- (B) Image-rich description page interspersed with explanatory text
- (C) Browse categories in sufficient number to illustrate the major highlights of the collection
- (D) Textual description of the collection in paragraph form.

I'm not sure we can really spell out guidelines until we have a vision for DPUL. Do we have a vision for DPUL? Some examples:

If it is a public-oriented digital collections site, we may want the home page to be (B) with a prominent link to a page like (A). a well-populated browse page (B) would probably be nice, as well.
This is my understanding of the site's purpose, but I'm not entirely sure.

If it is a researcher-oriented digital collections site, we may want (A) as the "home" page and something between (B) and (D) as the about page.

If it is an exhibits site, we may want (B) as the "home" page, a well-populated browse page (C) and a short or more-image-laden form of (D) as an about page.

If some collections may be one or the other, should we have some sort of decision tree leading to these various options?

In any case, I don't think we are well-served by the somewhat out-of-context facet list next to text with no images or images with no text, which is primarily what we have.

**Comment by hackmastera** [comment]
@escowles I started this doc but we'll need some direction before moving forward; please see above comment!

https://docs.google.com/document/d/14r_EbE--rQ3wsOYKI7Jv2iIatHfxsyOwk8PRKYu8g_0/edit#

**Comment by escowles** [comment]
@hackmastera I think we're talking about different things.  I haven't heard any request for comprehensive editorial guidelines that would lay out what the purpose of DPUL was and how each collection page fit into that.

I was thinking more of general guidelines like:

* Have a mixture of text and images on collection home pages to give them some context and visual interest
* When creating browse categories, consider creating categories for all of the primary collection strengths, rather than just one or two

Plus instructions (maybe videos?) for things typical tasks like:

* Configuring facet and metadata display
* Setting a banner image
* Adding additional users to edit the collection

**Comment by kelea99** [comment]
https://dpul.princeton.edu/exhibits_documentation

Once this is live, is it good enough for you to close this ticket, @hackmastera ?

**Comment by hackmastera** [comment]
I think the page is a good start. So far it seems like an orientation to the tool set. I think this ticket is more for advice on how to arrange layout elements.

**Comment by kelea99** [comment]
oh! Its all there in the faceting, Anna! including video demos on all the dashboard facets and page widgets, explanations at to what they are, how to use them, who to contact for information, how to use imported images versus uploaded items for mastheads and flippy cards etc. is this a ticket that is more for esthetic advice on what looks good and examples of other collections? I could make another page for useful links to other spotlight exhibits?

**Comment by kelea99** [comment]
im closing this ticket, assuming this takes care of it. @hackmastera  if you think it does not, please feel free to reopen and we can revisit :) https://dpul.princeton.edu/exhibits_documentation
