### ISSUE TITLE
"Total Items" for saved search is 2 higher than actual number of items

### ISSUE THREAD

**Issue by escowles** [pulibrary/pomegranate#332]
e.g., doing a blank search in the eastasian exhibit shows 203 items:

https://dpul.princeton.edu/eastasian/catalog?utf8=%E2%9C%93&exhibit_id=eastasian&search_field=all_fields&q=

But saving that search show an item count of 205:

https://dpul.princeton.edu/eastasian/browse/all-exhibit-items

**Comment by jrgriffiniii** [comment]
Also, the appropriate total is found within the Solr response body, hence this might be related to a persisted `Search` Model method failing to retrieve the correct number of Documents: https://dpul.princeton.edu/eastasian/browse/all-exhibit-items.json
