### ISSUE TITLE
Ephemera: Facet on series title

### ISSUE THREAD

**Issue by escowles** [pulibrary/pomegranate#345]
Russian poster sets will be entered as ephemera with a common series title.  Faceting on the title will allow building browse categories for them in DPUL.

**Comment by hackmastera** [comment]
@escowles Is this still relevant? We aren't seeing a series title field, e.g. in https://figgy.princeton.edu/catalog/19113c44-d739-439e-807b-e342894f2807

**Comment by escowles** [comment]
@hackmastera No, I think they decided on a different way of grouping these items. I'll go ahead and close this ticket.
