### ISSUE TITLE
configuring issues is not working

### ISSUE THREAD

**Issue by escowles** [pulibrary/pomegranate#354]
In DPUL trying to get an image for the thumbnail or masthead isn't working. I can select a title from the collection but no images actually appear.

Migrated from https://github.com/pulibrary/plum/issues/1496

**Comment by jrgriffiniii** [comment]
I have implemented a test suite which ensures that setting the thumbnail or masthead background properly functions: https://github.com/pulibrary/pomegranate/blob/a668c8ff54c851bf896bc58ee5180ec1a34849f7/spec/controllers/spotlight/appearances_controller_spec.rb

Regarding the user interface, does this relate to the dropdown selection UI component for selecting the image?  If so, from within the development environment, this does appear to function:

![pomegranate_issues_354_screenshot_0](https://user-images.githubusercontent.com/1443986/39710595-3dc7bf3c-51eb-11e8-8b00-5acf6b4d05fc.png)

![pomegranate_issues_354_screenshot_1](https://user-images.githubusercontent.com/1443986/39710610-46c275aa-51eb-11e8-9b1d-c9dfabbfaa54.png)

**Comment by escowles** [comment]
@joycebcat I just created a DPUL collection for ABC Books (https://dpul.princeton.edu/abc_books) and was able to create a masthead from at item in the collection.  Are you still seeing this problem, and if so, which collection(s) have the problem?

**Comment by tpendragon** [comment]
@kelea99 Have you had any issues adding banners etc? If not, I'd like to close this issue.

**Comment by kelea99** [comment]
@tpendragon Nope. I only had issue when the file size was too big (which was my fault, not yours). ok to close and thank you!
