### ISSUE TITLE
Stretched thumbnails in search results

### ISSUE THREAD

**Issue by jpstroop** [pulibrary/pomegranate#358]
![screen shot 2018-04-30 at 9 12 40 am](https://user-images.githubusercontent.com/999701/39429576-45556b24-4c59-11e8-9f79-5d81cacb857f.png)

**Comment by hackmastera** [comment]
@jpstroop It doesn't look stretched to me what am I missing? https://dpul.princeton.edu/catalog?utf8=%E2%9C%93&search_field=all_fields&q=balus

**Comment by hackmastera** [comment]
here are some examples of thin / wide thumbnails that I found, both of which seem okay to me:
https://dpul.princeton.edu/catalog?utf8=%E2%9C%93&search_field=all_fields&q=querencia

https://dpul.princeton.edu/catalog?utf8=%E2%9C%93&search_field=all_fields&q=book+of+the+dead

**Comment by escowles** [comment]
@hackmastera 👍  these look good to me (and I checked in Figgy and saw the same)
