### ISSUE TITLE
Update cover images to use Figgy JP2s instead of Plum's JP2s

### ISSUE THREAD

**Issue by escowles** [pulibrary/pomegranate#359]
Most of the exhibit cover images use JP2s from Plum.  Now that Plum has been retired, this constitutes a significant amount of the requests for those images, which could otherwise be deleted.

**Comment by tpendragon** [comment]
The figgy ones are hardlinks of the plum ones, so this shouldn't be a space problem, but it would look prettier for sure.

**Comment by hackmastera** [comment]
Do we expect this will be achieved via a database update?

**Comment by jrgriffiniii** [comment]
After reviewing https://github.com/projectblacklight/spotlight/blob/master/app/models/spotlight/exhibit_thumbnail.rb and https://github.com/projectblacklight/spotlight/blob/master/app/models/spotlight/featured_image.rb, it does seem feasible to address this as a database migration.  I assume that migrating the IIIF attributes would fully resolve this.

**Comment by hackmastera** [comment]
I would vote for a rake task that updates the database as opposed to a migration!

**Comment by jrgriffiniii** [comment]
Closed in response to https://github.com/pulibrary/pomegranate/pull/391#issuecomment-431121073
