### ISSUE TITLE
Metadata display for music

### ISSUE THREAD

**Issue by escowles** [pulibrary/pomegranate#360]
From Darwin:
> The example I’m looking at is the record for the Mozart sonata manuscript (known as [Sonata III}: https://catalog.princeton.edu/catalog/3511131 . We have some work to do yet on updating this metadata, but missing from the DPUL metadata are the following fields as they now stand:
 
> 240 – uniform title, which is crucial for this record to identify the actual work (Sonatas, piano, K. 332, F major). This field is really essential.
>
> A number of descriptive 500 fields:
> 546 – Language of text
> 563 – Binding note
> 561 – Provenance
> 541 – Source of acquisition

**Comment by tpendragon** [comment]
I've had to update metadata a couple times - I think this is the last time necessary for these fields to appear. It's firing events, so as the metadata's refreshed it should be updating DPUL.

**Comment by tpendragon** [comment]
These fields are imported and updated.
