### ISSUE TITLE
Child volumes are showing up in search results

### ISSUE THREAD

**Issue by escowles** [pulibrary/pomegranate#362]
For example:
* parent: https://dpul.princeton.edu/ealtoc/catalog/rv042x673
* child 1: https://dpul.princeton.edu/ealtoc/catalog/65a6860c-7fb3-48b9-84aa-7d27e545cfc1
* child 2: https://dpul.princeton.edu/ealtoc/catalog/b4624d8a-e94c-44cc-97e5-096a36be8d25

**Comment by tpendragon** [comment]
I think what's going on here is both the parent and the volumes are a member of the collection, so the volumes are showing up in the collection's manifest listing. A quick solution would be to suppress items from the full collection listing which have parents, but it would add quite a few queries to that view.

**Comment by hackmastera** [comment]
Reopening until the rake task has been run

**Comment by tpendragon** [comment]
This should be fixed - we should ask Tom if this is still happening.

**Comment by escowles** [comment]
This is fixed — I'm seeing the same counts for browse and blank search results for both the eastasian and ealtoc exhibits (which is how I was testing this before).  Tom V. confirms it's fixed.
