### ISSUE TITLE
Scheide related issue:  references sometimes displays gibberish

### ISSUE THREAD

**Issue by joycebcat** [pulibrary/pomegranate#367]
Some digital objects are displaying several lines of coding with the label "references", rather critically at the moment this includes our Gutenberg Bible.

https://dpul.princeton.edu/scheide/catalog/7d278t10z#?c=0&m=0&s=0&cv=0&xywh=-9882%2C-401%2C24996%2C8000

**Comment by joycebcat** [comment]
Actually, I haven't seen any record with data attached to this label which is of any benefit.  Is the solution here just to suppress it from display?

The label "references" was making me think it would/could hold something useful.

**Comment by tpendragon** [comment]
I think we should probably just suppress this from bibdata's JSON-LD view so it never gets imported.

**Comment by jrgriffiniii** [comment]
Resolved by https://github.com/pulibrary/marc_liberation/pull/405
