### ISSUE TITLE
Scheide related issue: uniform titles / choice of main title display

### ISSUE THREAD

**Issue by joycebcat** [pulibrary/pomegranate#369]
Darwin's issue 360 is related to this.  That ticket mentions the lack of 240 field, but uniform titles from 130 fields are not in DPUL either.  These fields have important variations which are often not covered anywhere else in the record.

The choice of the main title to show at the top of the display should be considered when this data is incorporated.  It isn't an obvious decision because of the degree of variation in what is used as a uniform title.  The best option is probably a combination of the 245 title and the uniform title.

An enhancement for very specialist material, like the Scheide collection, is the ability to put in an override title *in DPUL* which would be used for the primary display.  Paul Needham has asked for this, it seems reasonable to me for the purposes of bridging the gap between cataloging standards and the particular needs of the DPUL site.  (Note: this was discussed as a potential future enhancement, it is not highly time-critical)

**Comment by tpendragon** [comment]
I think we can close this and #360 if we map add a `uniform_title` field in bibdata's JSON-LD which maps to `uniform_title_s`.
