### ISSUE TITLE
Allow display title to be modified by curator

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/pomegranate#375]
Request from @joycebcat:
> An enhancement for very specialist material, like the Scheide collection, is the ability to put in an override title in DPUL which would be used for the primary display. Paul Needham has asked for this, it seems reasonable to me for the purposes of bridging the gap between cataloging standards and the particular needs of the DPUL site. (Note: this was discussed as a potential future enhancement, it is not highly time-critical)

**Comment by escowles** [comment]
@jrgriffiniii:
> The Welcome Additions Collection requires a custom curator-provided label to be used in favor of the Voyager-imported values for the item title
