### ISSUE TITLE
Item import is generating a ton of readonly_alternative_ssim fields

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/pomegranate#396]
This is slowing page generation significantly.

**Comment by jrgriffiniii** [comment]
The `document_builder` may actually be the cause of this: https://github.com/projectblacklight/spotlight/blob/0ff14576f874/app/models/spotlight/resource.rb#L52

**Comment by tpendragon** [comment]
There are 452 `readonly_alternative_ssim` `Spotlight::CustomField` fields in DPUL production right now.

**Comment by tpendragon** [comment]
This was a data problem. For some reason an old field had messed up the blacklight config, so it wasn't detecting that `Alternative` already had a custom field for a given exhibit. It was broken for Scheide. I deleted the extras, forced the label to be `Alternative` from `Alternative title` and it's playing nice now.

The fix:

```ruby
exhibit = Spotlight::Exhibit.where(id: 18).first
custom_fields = exhibit.custom_fields.where(field: "readonly_alternative_ssim")
custom_field = custom_fields.last
custom_field.label = "Alternative"
custom_field.save
custom_fields[0..416].map(&:destroy)
```
