### ISSUE TITLE
improve usability of facets on collection home pages

### ISSUE THREAD

**Issue by hackmastera** [pulibrary/pomegranate#399]
The facets without any search results seem confusing. Can they be restyled somehow? A "browse" heading (although this might conflict with the existing browse functionality)? With sufficient browse categories perhaps it makes sense to remove them entirely?

**Comment by escowles** [comment]
@hackmastera I don't see any facets on the DPUL home page, or a search with no search results.  Should this ticket be in OL?

**Comment by hackmastera** [comment]
I was referencing a "home" page for a collection, e.g. https://dpul.princeton.edu/pudl0058

**Comment by sdellis** [comment]
It seems that all facets must have at least one result. Are there some facets with no results?

**Comment by escowles** [comment]
@sdellis Blacklight only returns facet values with at least one hit, and facet categories with at least one value.  So any facets without any values won't be displayed.  Which facets are displayed is also configurable, so that will change which ones are displayed.

**Comment by sdellis** [comment]
@escowles I think I misunderstood the issue then. Is there confusion around facets with only one result?

**Comment by hackmastera** [comment]
By "the facets without any search results" I meant that there is a list of facets but there isn't a search results area. What are they faceting? what's on the page is usually general intro language about the collection.

**Comment by hackmastera** [comment]
fwiw, i'm in favor of removing them and making these pages more like general overview guides of what's in the collection, with links to search results or browse results in the body of the page.

**Comment by tpendragon** [comment]
It's interesting this hasn't come up in the context of the Catalog home page. I agree, but we should do user testing.

**Comment by sdellis** [comment]
This has come up in the context of the Catalog home page, but it was a long time ago when we were initially moving to Orangelight. Of course, at the time there was some resistance to too much customization on that page, particularly since there were much bigger "fish to fry" when rolling out the new catalog.

**Comment by tpendragon** [comment]
Thanks for that background @sdellis!

**Comment by hackmastera** [comment]
These can be removed on a per-collection basis.
