### ISSUE TITLE
Can we have one pomegranate?

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/pomegranate#4]
Multi-tenancy work? Can we change the design between each exhibit?

**Comment by tpendragon** [comment]
MAYBE. As-is, you can't change the design between each exhibit - all you can change is the masthead.

**Comment by jpstroop** [comment]
Say we had 50 "exhibits", or 100. Are there other concerns, e.g. regarding scalability? If not, let's see how far we can get with one instance.

Out of curiosity, does one instance mean we can search-across as well? Or Does each exhibit still need a separate Solr core?

**Comment by escowles** [comment]
Not being able to change the design seems pretty limiting -- being able to configure a custom CSS file seems like it would be 1) not that hard to implement and 2) cover a lot of popular customization options (font, colors, etc.)

**Comment by jpstroop** [comment]
That's sort of where my head was going too. As long as they don't want to change the layout, there may be something we can do. I can't exactly see how an impl would work, but maybe introducing a notion of Themes that are basically sets of values for known CSS classes...something like that.

**Comment by escowles** [comment]
I was thinking of having CSS files named after the collection slug.  So the layout would check to see if a CSS file existed for the collection and include it if so.  Depending on the workflow and who would be editing these CSS files, they could be in the app itself, or in a separate directory.

**Comment by jpstroop** [comment]
So we'd still commit a designer/developer, potentially? I was thinking of something the curator could do, either by choosing an existing theme or making a new one.

**Comment by escowles** [comment]
Yes, either a designer/developer would need to create the CSS file, or we'd need to trust the curator to be able to do that.  Maybe the first step is to have a manually-created CSS file, and the second step is to create a GUI tool where you have a color picker, font menu, etc. that generates the CSS file?

**Comment by jpstroop** [comment]
That could be cool...anyway, seems like we have options.

**Comment by tpendragon** [comment]
> I was thinking of having CSS files named after the collection slug.

The way I've always done this is just putting the slug as a class name on the body, and then having themes play off of that parent class.

**Comment by tpendragon** [comment]
> Out of curiosity, does one instance mean we can search-across as well? Or Does each exhibit still need a separate Solr core?

Yes, there's one solr core and each item has an exhibit key which determines which exhibit it's a member of. I'm not sure if there's a built-in "search-across", but it's possible.

**Comment by kevinreiss** [comment]
The need for a curator to create their own CSS hasn't been a use case that has come up in the past. Beyond customizing the masthead and deciding what content and layout to use on the homepage most questions of customization have come about labeling metadata fields and choosing the order in which objects are displayed on thematic section pages like http://rbsc.princeton.edu/versailles/palace. 

It would definitely be good to have a pattern in place that would allow a developer/designer to include some CSS to give a custom treatment to exhibition but I think the application having sensible defaults for colors, fonts, spacing, masthead customization, and a couple of well thought out layout choices available for landing and thematic pages will probably cover 98% of our use cases.

**Comment by tpendragon** [comment]
Assuming yes until this falls apart.
