### ISSUE TITLE
Keep Dublin Core extension enabled?

### ISSUE THREAD

**Issue by christinach** [pulibrary/pomegranate#423]
## Backtrace

    line 13 of [PROJECT_ROOT]/app/repositories/friendly_id_repository.rb: find
    line 79 of [PROJECT_ROOT]/app/controllers/catalog_controller.rb: show

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/51733/faults/39599386)

**Comment by eliotjordan** [comment]
The Honeybadger error that brought this to light is resolved, however, it brought to light that we have the DublinCore extension enabled but it returns an empty document.

https://github.com/pulibrary/pomegranate/blob/master/app/models/solr_document.rb#L21
https://dpul.princeton.edu/catalog/jm214q536.oai_dc_xml

Should keep this enabled?

**Comment by escowles** [comment]
I don't think there's any value to keeping an empty document around — I think we should disable the DC extension.
