### ISSUE TITLE
Problems exist with the diacritics for certain item metadata views

### ISSUE THREAD

**Issue by jrgriffiniii** [pulibrary/pomegranate#425]
I failed to reproduce this on my local environment (Google Chrome 69.0.3497.100 on macOS Sierra 10.12.6), but as reported:
> The font used does not display diacritics (macrons at least) directly above the character
https://dpul.princeton.edu/catalog/n009w555s#?c=0&m=0&s=0&cv=0&xywh=-6977%2C-339%2C21153%2C6770

I found the following rendered for this item:
<img width="1136" alt="dpul_macron" src="https://user-images.githubusercontent.com/1443986/46161025-52f9a780-c252-11e8-8f78-ac7d8d7ee1a1.png">

**Comment by jrgriffiniii** [comment]
This appears to only affect certain browsers (possibly only within certain operating system environments):

> no actually that one is fine.  I am seeing the problem using the latest versions of FF and IE on a Win7 PC

![macron](https://user-images.githubusercontent.com/1443986/46162522-88a08f80-c256-11e8-8208-3361bdb6d24b.png)

**Comment by escowles** [comment]
I see a mis-aligned diacritic in Firefox, but only in the attribute list, not the page header:
<img width="238" alt="screen shot 2019-01-08 at 3 54 11 pm" src="https://user-images.githubusercontent.com/856924/50858325-13b51980-135e-11e9-92bd-8fca23fb1bc5.png">

Both the page header and the attribute list display correctly in Chrome.
