### ISSUE TITLE
Allow curators to add a block of text to item show pages

### ISSUE THREAD

**Issue by escowles** [pulibrary/pomegranate#432]
This is to support the Welcome Additions exhibit.

**Comment by jrgriffiniii** [comment]
Currently persistence is now functioning on my branch:

<img width="569" alt="pomegranate_issues_432_screenshot_0" src="https://user-images.githubusercontent.com/1443986/49160237-4ea24700-f2f4-11e8-86da-d15920d4121f.png">

However, I am uncertain as to how this should be enabled/disabled for a given custom field.  I can look to offer the following:

<img width="869" alt="pomegranate_issues_432_screenshot_1" src="https://user-images.githubusercontent.com/1443986/49160241-5104a100-f2f4-11e8-9d03-834d63523132.png">

Would this be disorienting to users?  If not, I can look to implement this as well.

**Comment by hackmastera** [comment]
it might also be good to ask users about the field label; see whether "curation note" conveys that it will be the added display text

**Comment by escowles** [comment]
I think having display of the Curation Note be enabled/disabled in the existing metadata display configuration would be great.

I'll ask Eric if "Curation Note" is a good label for the field — they are also preparing physical labels for the exhibited items, and they may have terminology for this field already.
