### ISSUE TITLE
Make IIIF manifests more accessible

### ISSUE THREAD

**Issue by escowles** [pulibrary/pomegranate#439]
e.g., create a drag-and-drop icon:

* https://zimeon.github.io/iiif-dragndrop/
* logo: https://drive.google.com/drive/u/0/folders/0B8APFBow4sHvY044Sm10SFdNWG8

**Comment by tpendragon** [comment]
Duplicate of #262?

**Comment by tpendragon** [comment]
Duplicate of #262?

**Comment by escowles** [comment]
Closing in favor of #262
