### ISSUE TITLE
content-block item-grid-block row displays html

### ISSUE THREAD

**Issue by christinach** [pulibrary/pomegranate#460]

**Comment by christinach** [comment]
<img width="1265" alt="screen shot 2018-11-30 at 9 52 42 am" src="https://user-images.githubusercontent.com/9905193/49296254-b936bc80-f485-11e8-961d-1f819b90a7aa.png">

**Comment by escowles** [comment]
This commit broke display of thumbnails: https://github.com/pulibrary/pomegranate/commit/fc56018ef47b8fb5e1b6ec45ff88275c5fb7e13c
