### ISSUE TITLE
Add brief descriptive text to DPUL home page

### ISSUE THREAD

**Issue by kelea99** [pulibrary/pomegranate#466]
Any thoughts on adding brief descriptive text somewhere on DPUL landing page, explaining what DPUL actually is?  Something like (take/leave/edit as you see fit): Digital...(DPUL) is a curated set of online collections that represents highlighted selections of material from Princeton's full corpus of digital content..."?

child of #440

**Comment by kelea99** [comment]
@escowles I've added a subtitle to the main masthead for DPUL, but it is not showing. Can we turn this on? Added here versus opening a new ticket. 
![Screen Shot 2019-09-19 at 11 26 46 AM (3)](https://user-images.githubusercontent.com/45043014/65259305-773d3c80-dad2-11e9-9aa3-bebc472092aa.png)

**Comment by escowles** [comment]
I believe this is fixed by https://github.com/pulibrary/pomegranate/pull/612 — which we will deploy shortly.
