### ISSUE TITLE
User can't click "site thumbnail" tab while Figgy is open in another tab in Firefox

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/pomegranate#471]
Reported by @roelmoon:

> I’m encountering that weirdness with figgy and DPUL in tabs. I’m logged into both. I’m trying to look at the “site thumbnail” so I can download the tiff from Figgy but DPUL dashboard won’t let me switch from “site masthead” while in configuration/appearance. Works fine in separate windows. Using Mac/Firefox.

![dpul](https://user-images.githubusercontent.com/2806645/49762438-9b840700-fc7e-11e8-8717-b44140a3f242.jpg)

**Comment by hackmastera** [comment]
I was unable to replicate this bug; it seems as though it may have been resolved. Please reopen and let me know if it occurs again; I'd like to see what this looks like.
