### ISSUE TITLE
Replace 500 with friendly error message when user tries to create a page that already exists

### ISSUE THREAD

**Issue by hackmastera** [pulibrary/pomegranate#474]
[Pomegranate/production] ActiveRecord::RecordNotUnique: PG::UniqueViolation: ERROR:  duplicate key value violates unique constraint "index_friendly_id_slugs_on_slug_and_sluggable_type_and_scope"DETAIL:  Key (slug, sluggable_type, scope)=(about, Spotlight::Page, exhibit_id:30) already exists.: INSERT INTO "friendly_id_slugs" ("slug", "sluggable_id", "sluggable_type", "scope", "created_at") VALUES ($1, $2, $3, $4, $5) RETURNING "id"

## Backtrace

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/51733/faults/42854730)

**Comment by escowles** [comment]
I wasn't able to reproduce this — I've asked the user who encountered this error (Kim) if she remembers it.

**Comment by tpendragon** [comment]
This hasn't happened since. I'm going to close it.
