### ISSUE TITLE
Allow disabling thumbnail display

### ISSUE THREAD

**Issue by escowles** [pulibrary/pomegranate#475]
For items without thumbnails, or where the thumbnails are of very poor quality, it would be nice to suppress them from the search results page.

**Comment by escowles** [comment]
Tom Ventimiglia asked for this, because the EAL table of contents images display very poorly as thumbnails.

**Comment by escowles** [comment]
See https://dpul.princeton.edu/ealtoc/catalog?utf8=%E2%9C%93&exhibit_id=ealtoc&search_field=all_fields&q= for example search results with many items with useless thumbnails.

**Comment by tpendragon** [comment]
Close this ticket by adding a configuration option to an exhibit to disable thumbnail display for all items in that exhibit.
