### ISSUE TITLE
Fix reindexing UI

### ISSUE THREAD

**Issue by hackmastera** [pulibrary/pomegranate#485]
The reindexing jobs all get queued, but the progress bar never progresses, and then it sort of disappears at some point even though the jobs are not finished.

**Comment by eliotjordan** [comment]
Possible solutions:

1. Run entire reindex process in one job, like in vanilla Spotlight.
1. Hide the job progress bar.
1. Create a database object to save the job ids as they're spawned and query sidekiq API from a javascript.
1. Periodically query Sidekiq API to find IIIFIngest Jobs with the corresponding exhibit id. We will need to override the resources monitor route. This would only give an estimated count of completed items. We can tell when the queue is empty, but not when all jobs are processed.

**Comment by eliotjordan** [comment]
We pursued database locking in this branch:  https://github.com/pulibrary/pomegranate/tree/485-fix-indexing

**Comment by escowles** [comment]
Using database logging sounds like a good way to track this (better than using the Sidekiq API, IMHO).
