### ISSUE TITLE
Improve the masthead and landing page for the Welcome Additions

### ISSUE THREAD

**Issue by jrgriffiniii** [pulibrary/pomegranate#489]
This might be structured to resemble the promotional material (a pamphlet) for the physical exhibitions

**Comment by kelea99** [comment]
Eric liked the idea of structuring the site to reflect the sections of the pamphlet (via facets in side nav bar): Cotsen, EAL, GA, MSS, Marquand, Numismatics, Public Policy, Rare Books, Scheide, University Archives, Western Americana.

**Comment by escowles** [comment]
@kelea99 will create the browse categories and setup the home page — this ticket is for CSS changes she would like to go with that.

**Comment by kelea99** [comment]
[WA-DPUL-enhancements_KEL_list.pdf](https://github.com/pulibrary/pomegranate/files/2871027/WA-DPUL-enhancements_KEL_list.pdf)

**Comment by tpendragon** [comment]
@kelea99 The links in that PDF don't seem to work for me. They working for you?

**Comment by kelea99** [comment]
Lemme check, @tpendragon . One sec

**Comment by kelea99** [comment]
Can we get the main container on the home page of WA  to just be 1 row (see: https://exhibits.stanford.edu/parker) and the flexbox for the curator headshots for the curator page  working by Wednesday or Thursday of this week? Curator page: 
![curator_page_mockup05](https://user-images.githubusercontent.com/45043014/53346903-d506fe80-38cc-11e9-94a8-0eb694864cdd.jpg)

**Comment by escowles** [comment]
Closing this ticket since the Welcome Additions home page issue was addressed, and #531 is still open for tracking the curator photo feature.
