### ISSUE TITLE
Update footers to match Orangelight/main Library site

### ISSUE THREAD

**Issue by escowles** [pulibrary/pomegranate#494]
See https://github.com/pulibrary/pomegranate/issues/440#issuecomment-461920307

**Comment by jrgriffiniii** [comment]
I haven't been able to ensure that the alignment between the styling is precise, but I've mostly resolved this for issues in the header:

<img width="1335" alt="pomegranate_issues_494_screenshot_0" src="https://user-images.githubusercontent.com/1443986/52642598-544a0a80-2ea9-11e9-8927-5b9e6cc5cf45.png">

<img width="1349" alt="pomegranate_issues_494_screenshot_1" src="https://user-images.githubusercontent.com/1443986/52642606-5613ce00-2ea9-11e9-9718-0e1bde40453f.png">

Regarding blockers for this issue, I've attempted to integrate LUX simply using a CDN (please see https://pulibrary.github.io/lux/docs/#/Installing%20LUX), but have encountered https://github.com/pulibrary/lux/issues/158.  Hence, this work needs to integrate Webpacker.

**Comment by escowles** [comment]
@jrgriffiniii Just to make sure, this ticket is for updating the *footers*:

DPUL:
![dpul-footer](https://user-images.githubusercontent.com/856924/52653532-1d322400-2ebe-11e9-908c-aec203875a89.png)

Catalog:
![catalog-footer](https://user-images.githubusercontent.com/856924/52653533-1d322400-2ebe-11e9-8443-ba30c9fea86d.png)

If Lux works, using it is fine.  But just updating the footers like we did for OL would be fine too: https://github.com/pulibrary/orangelight/pull/1556
