### ISSUE TITLE
Pages Widget currently only allows for 3 highlighted pages thumbnails within widget in DPUL

### ISSUE THREAD

**Issue by kelea99** [pulibrary/pomegranate#497]
Needed: 12 thumbnails for highlighted (curators) pages to be viewed  on home page of Welcome Additions.  See https://dpul.princeton.edu/wa

**Comment by escowles** [comment]
Can you create four of the existing page widgets, one after the other, to achieve a 4x3 grid?

**Comment by kelea99** [comment]
sigh. could have thought this out better. Yes!! thanks :)

**Comment by escowles** [comment]
No worries — happy to help you figure out how to use what's there already!
