### ISSUE TITLE
Header is missing from exhibits

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/pomegranate#501]
<img width="1429" alt="screen shot 2019-02-12 at 10 50 29 am" src="https://user-images.githubusercontent.com/2806645/52660197-0f77a100-2eb4-11e9-807a-9b1e4f435cdf.png">

Happened after #499

Without it, users can't log in/out or navigate to the front page.

**Comment by escowles** [comment]
Also, the page title is including the exhibit title instead of just "Digital PUL" — resulting in line-wrapping.

![screen shot 2019-02-12 at 1 57 29 pm](https://user-images.githubusercontent.com/856924/52660686-3511a400-2ece-11e9-922b-8af7334fb77b.png)

**Comment by jrgriffiniii** [comment]
I've tried retaining turbolinks support by using https://github.com/jeffreyguenther/vue-turbolinks/blob/master/README.md (it was recommended on https://github.com/turbolinks/turbolinks/wiki/VueJs-and-Turbolinks).  This created some form of error with the Webpack compilation that I'm still struggling to address.

**Comment by jrgriffiniii** [comment]
Trying to update `webpack-dev-server` beyond 2.11.x releases (to anything beyond 3.0.0) introduces the following bug: https://github.com/rails/webpacker/issues/1303.  Most on this thread simply reverted to 2.9.x:

```
i'm having the same problem of
`cannot destructure property compile of 'undefined' or 'null'`
and my solution is at [webpack/webpack-dev-server#1259](https://github.com/webpack/webpack-dev-server/issues/1259) @smackgg

with this command: `npm install --save-dev webpack-dev-server@2.9.7`
```
(Please see https://github.com/rails/webpacker/issues/1303#issuecomment-450461654)

I'll look to resolve this also.
