### ISSUE TITLE
Browse categories page is really, really slow.

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/pomegranate#523]
Takes ~ 8 seconds to load. Datadog says it's stuck rendering a partial for over six seconds, but won't say which.

**Comment by tpendragon** [comment]
https://app.datadoghq.com/apm/resource/pomegranate/rack.request/3957ae38050ceea1?end=1550618988587&env=none&graphType=span_list&paused=false&spanID=1827233406679838974&start=1550014188587&traceID=4499945535634042003

It also runs a query for the exhibit 2600 times and for the blacklight config for a given exhibit 1300 times. :|

**Comment by hackmastera** [comment]
Still slow but it's more like 1 second which we can live with
