### ISSUE TITLE
Widget to embed curator photo on feature page

### ISSUE THREAD

**Issue by escowles** [pulibrary/pomegranate#531]
Enable embedding curator photo with caption on a feature page.  See mockup in https://github.com/pulibrary/pomegranate/issues/489#issuecomment-467048563

**Comment by escowles** [comment]
@kelea99 Is using the uploaded item widget good enough here? I've updated the Cotsen page: https://dpul.princeton.edu/wa/feature/cotsen-children-s-library

**Comment by kelea99** [comment]
@escowles is it possible to wrap the text around widget containing curator photo versus: 
![screen shot 2019-02-25 at 5 11 25 pm 3](https://user-images.githubusercontent.com/45043014/53372291-4d8ab100-3907-11e9-8687-95860fd273da.png)

**Comment by kelea99** [comment]
![curator_pg_screenshot](https://user-images.githubusercontent.com/45043014/53441815-a163cb80-39d5-11e9-9fbf-b165af595424.jpg)
@christinach

**Comment by christinach** [comment]
Thanks @kelea99 !

**Comment by tpendragon** [comment]
This was high priority for the Welcome Additions exhibit, but I think it got worked around, so I'm removing the label. If this is in error please re-add it.

**Comment by kelea99** [comment]
@tpendragon we got it worked around.
