### ISSUE TITLE
If there are no facets, the content should align with the H of "home" within the nav bar 

### ISSUE THREAD

**Issue by kelea99** [pulibrary/pomegranate#532]

**Comment by escowles** [comment]
Currently, space is being reserved for the facets (even if none are displayed), pushing the content on the exhibit home page over to the right.

**Comment by kelea99** [comment]
@escowles, is it possible to get this ready by tomorrow morning?

**Comment by escowles** [comment]
I just figured out how to fix this — on each page, you can go to the Edit mode, and there is an "Options" tab at the top, where you can turn of displaying the sidebar.  I've done that for the WA home page, and now the content is aligned without a big blank space for the non-existent sidebar.
