### ISSUE TITLE
Allow pomegranate:reindex Rake task to be used in production

### ISSUE THREAD

**Issue by escowles** [pulibrary/pomegranate#533]
- [x] Move the `pomegranate:reindex` task out of the `dev.rake` which is only loaded in dev/test environments
- [x] Use `IIIFResource.find_or_initialize_by` instead of `find_by` to allow initial indexing with the Rake task
- [x] Allow finding the resource by noid, for items that have already been indexed once
- [x] add a task that commits the index

**Comment by hackmastera** [comment]
seems like it would be nice to have a task that takes a noid, as well as one that could do an initial index.

**Comment by escowles** [comment]
Also, as long as we're updating our indexing Rake tasks, it would be good to have a task that commits the index, since we've disabled commits in our code, and autocommits take a long time.
