### ISSUE TITLE
Curatorial note is not showing up for items in DPUL WA exhibit

### ISSUE THREAD

**Issue by kelea99** [pulibrary/pomegranate#535]
![screen shot 2019-02-28 at 10 59 53 am 3](https://user-images.githubusercontent.com/45043014/53579679-03dcd900-3b48-11e9-8c9d-265b48a78518.png)

looked in metadata fields under config and both the title override and curatorial note are there for collection specific fields. Ideas why curatorial note is not showing?

**Comment by escowles** [comment]
I went to that item, and the curatorial note field was there, but empty.  I added some test text and it's showing up for me now: https://dpul.princeton.edu/wa/catalog/x633f4984

**Comment by kelea99** [comment]
I see that too. So that's good. Did the curatorial notes not get bulk updated?

**Comment by escowles** [comment]
I checked a few other items, and it looks like the curatorial notes are not showing up.  I'll see why that didn't work.

**Comment by escowles** [comment]
I've found the problem — it looks like the format for entering the data in the database is a little different for a text block than it is for a regular field.  So my script entered the regular field format, but that's not being picked up by the text block.

Are there any more items with labels that I can update now, or should I just re-do the ones I did earlier?

**Comment by escowles** [comment]
I went ahead and updated the curator notes and they are displaying now.  One related issue I wanted to ask about: we recently added a feature where long values (over 300 characters) are truncated with a "More" link to expand them. Most of the notes and some of the custom titles are longer than this.  Should we increase the limit?  For reference, the longest notes (the Napoleonic medals that's not matched to an object yet), is 2500 characters. Many are ~1000 characters.

**Comment by kelea99** [comment]
let me have a look, but yes. I would say for WA exhibit we should up the character limit so that all are expanded (no "more" link).  We could disregard the numismatics labels, since we made browse cats for those with the complete note there, and take the maximum character limit of what's left. Sound good?

**Comment by escowles** [comment]
I've deployed an update to DPUL that increases the limit to 1200 characters, so the longer curators notes are not truncated now: https://dpul.princeton.edu/wa/catalog/hm50tw67k
