### ISSUE TITLE
Issue with CSS for DPUL footer

### ISSUE THREAD

**Issue by kelea99** [pulibrary/pomegranate#539]
![screen shot 2019-03-01 at 10 12 06 am 3](https://user-images.githubusercontent.com/45043014/53647008-8fb73980-3c0a-11e9-918b-5169a09cfaed.png)

The footer doesn't appear to be fixed.

**Comment by escowles** [comment]
👍 I'm seeing this too — the header is centered and grows a bit as you expand the page width, but the footer stays on the left.

**Comment by kelea99** [comment]
FYI Footer also moves vertically depending on the content within the main container of the page.
