### ISSUE TITLE
[Pomegranate/production] IIIFResource::IndexingError: Failed to update Solr for the following documents: e833fd0a2e50fa2e9b779748fd3befd5

### ISSUE THREAD

**Issue by hackmastera** [pulibrary/pomegranate#543]
## Backtrace

    line 68 of [PROJECT_ROOT]/app/models/iiif_resource.rb: rescue in write_to_index
    line 59 of [PROJECT_ROOT]/app/models/iiif_resource.rb: write_to_index
    line 33 of [PROJECT_ROOT]/app/jobs/spotlight/reindex_job.rb: block in perform

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/51733/faults/46031444)

**Comment by hackmastera** [comment]
There are 193 of these failures in sidekiq right now.

**Comment by hackmastera** [comment]
I think these are the objects with the bad references data. I tried pulling one into dev and it came through fine.

**Comment by eliotjordan** [comment]
This is still an issue. New occurrence re-opened the honeybadger error.

**Comment by jrgriffiniii** [comment]
Resolving these issues should be attempted by deleting old `SolrDocumentSidecars`, which can be attempted by invoking the following with the Rails console:
```
sidecar = Spotlight::SolrDocumentSidecar.find_by(document_id: BAD_SOLR_DOCUMENT_ID)
sidecar.delete
```

**Comment by tpendragon** [comment]
I think we've fixed this by cleaning up stale sidecar data. Resolved and marking this complete.
