### ISSUE TITLE
Viewer will not resize after exiting 'full screen'

### ISSUE THREAD

**Issue by christinach** [pulibrary/pomegranate#556]

**Comment by christinach** [comment]
![screen shot 2019-03-06 at 1 08 31 pm](https://user-images.githubusercontent.com/9905193/53903156-f5dbfc00-4010-11e9-8e49-c27729fcbffb.png)

**Comment by christinach** [comment]
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/9905193/53903222-2a4fb800-4011-11e9-88d8-b5482e543e8a.gif)

**Comment by christinach** [comment]
It will resize if you click the `esc` button again.

**Comment by tpendragon** [comment]
This looks fixed to me now (probably because of the viewer upgrade.) Can you confirm and close @christinach?

**Comment by christinach** [comment]
@tpendragon, it looks good now.
