### ISSUE TITLE
Footer should be outside of the main-content in search results

### ISSUE THREAD

**Issue by christinach** [pulibrary/pomegranate#558]

**Comment by christinach** [comment]
creates a left right margin
![screen shot 2019-03-07 at 9 49 16 am](https://user-images.githubusercontent.com/9905193/53964964-51b08e80-40be-11e9-831a-8c1ea8d4e4bf.png)

**Comment by escowles** [comment]
Is this the same as #546?

**Comment by christinach** [comment]
I opened it for the left right margins but maybe it has to do with the bottom also.

**Comment by christinach** [comment]
I think yes some tags are open. updating
