### ISSUE TITLE
Add Bookmarks and CSV download functionalities to DPUL

### ISSUE THREAD

**Issue by kelea99** [pulibrary/pomegranate#567]
This also came up during the 15M ephemera meeting I had with Fernando yesterday. can we have it mirror that of the catalog? ![Screenshot_bookmarks-downloads](https://user-images.githubusercontent.com/45043014/54833471-8d3d8200-4c94-11e9-828e-b105a6f141a9.png)

**Comment by hackmastera** [comment]
Current spotlight doesn't appear to override this anywhere, so it's worth just trying to turn this on in the usual blacklight way.

**Comment by hackmastera** [comment]
Seems like we could revert the commits that closed #190 and #139

**Comment by hackmastera** [comment]
here's the PR that added CSV to OL https://github.com/pulibrary/orangelight/pull/1491

**Comment by tpendragon** [comment]
Created #567 to add the CSV functionality. Closing this.
