### ISSUE TITLE
not all images showing up on flippy cards in DPUL main page

### ISSUE THREAD

**Issue by kelea99** [pulibrary/pomegranate#569]
example: 
![Screen Shot 2019-04-10 at 12 57 40 PM (3)](https://user-images.githubusercontent.com/45043014/55898324-57533580-5b90-11e9-8879-7910001e2b86.png)

**Comment by kelea99** [comment]
masthead images for the collections are not appearing as well.

**Comment by escowles** [comment]
This was a problem with multiple servers not sharing uploaded images.
