### ISSUE TITLE
RIIIF should return a 404 when an image isn't found, not throw an error.

### ISSUE THREAD

**Issue by jrgriffiniii** [pulibrary/pomegranate#574]
## Backtrace

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/51733/faults/48123631)

**Comment by jrgriffiniii** [comment]
It doesn't appear to be the case that this could be handled with a proper 404 response without overriding the `ImageController` for the `riiif` Gem.  Should `riiif` be still be being accessed within the production environment for DPUL?  If so, I can look to address this by submitting a pull request upstream.

**Comment by hackmastera** [comment]
It looks like it does 404 at least at one point.
https://github.com/curationexperts/riiif/blob/9dcd95f06f1dbac49cc5fa6eea6b1bc3f224efb9/app/controllers/riiif/images_controller.rb#L18

It seems difficult to proceed on this issue without the honeybadger trace. I propose we close it, as the underlying problem (shared network drive) has been resolved.

**Comment by tpendragon** [comment]
Sounds good to me
