### ISSUE TITLE
[Pomegranate/production] ActionView::Template::Error: undefined method `manifest' for nil:NilClass

### ISSUE THREAD

**Issue by jrgriffiniii** [pulibrary/pomegranate#575]
## Backtrace

    line 89 of [PROJECT_ROOT]/app/helpers/application_helper.rb: universal_viewer
    line 67 of [PROJECT_ROOT]/app/helpers/application_helper.rb: universal_viewer_url
    line 2 of [PROJECT_ROOT]/app/views/catalog/_universal_viewer_default.html.erb: _app_views_catalog__universal_viewer_default_html_erb__3869454880415577041_70024025716380

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/51733/faults/48191351)

**Comment by christinach** [comment]
https://github.com/pulibrary/pomegranate/issues/588
