### ISSUE TITLE
I would like to see an option for the curatorial note to also be added below the hyperlink title override to an exhibit item in the browse listing

### ISSUE THREAD

**Issue by kelea99** [pulibrary/pomegranate#587]
a question was raised by Stephanie Weiner if this would be possible for future DPUL exhibitions being built to accompany a physical exhibit. She would like to see all curatorial content with the hyperlinked title override and thumbnail in the browse listing as an option.   See screenshot: 
![Curatorial_note_batchmigrate](https://user-images.githubusercontent.com/45043014/58193000-06a32200-7c90-11e9-949b-1d2300383122.jpg)

**Comment by tpendragon** [comment]
@kelea99 Is this a private note like https://github.com/pulibrary/pomegranate/issues/87 or just an additional metadata field?

**Comment by tpendragon** [comment]
I spoke with @kealea99. This is already possible by going into the metadata configuration and clicking the checkbox for "List" next to Curatorial Note. Adding a screenshot and closing this issue.
![Screen Shot 2019-05-22 at 1 16 54 PM](https://user-images.githubusercontent.com/2806645/58207165-fa6e9300-7c96-11e9-86b2-c0757f773a54.png)
