### ISSUE TITLE
Server Error encountered when adding an item imbed to DPUL unpublished collection

### ISSUE THREAD

**Issue by kelea99** [pulibrary/pomegranate#588]
occurred when we tried to save after adding item embed widget to page. 

<img width="1440" alt="Screen Shot 2019-05-29 at 1 05 17 PM" src="https://user-images.githubusercontent.com/45043014/58576634-c6551e00-8212-11e9-827b-fb70003cc81f.png">

**Comment by christinach** [comment]
https://app.honeybadger.io/projects/51733/faults/48191351

**Comment by kelea99** [comment]
hey @christinach . I tried another this evening for a different DPUL exhibition and got the following: 
<img width="1440" alt="Screen Shot 2019-05-29 at 10 03 07 PM" src="https://user-images.githubusercontent.com/45043014/58603190-da723d00-825d-11e9-9344-3daf482ae7ad.png">

**Comment by kelea99** [comment]
from trying to do this: 
<img width="1440" alt="Screen Shot 2019-05-29 at 10 03 22 PM" src="https://user-images.githubusercontent.com/45043014/58603226-fc6bbf80-825d-11e9-8b73-c48410c8a375.png">

**Comment by christinach** [comment]
@kelea99 reported that removing the `item embed widget` removed the error. we need to check the widget
