### ISSUE TITLE
Resources marked as "Private" in Figgy are indexed into DPUL

### ISSUE THREAD

**Issue by jrgriffiniii** [pulibrary/pomegranate#589]
https://dpul.princeton.edu/msstreasures/catalog/44558h891 was indexed in response to https://figgy.princeton.edu/catalog/6717f91a-c1f9-473a-8e62-25d6d6a1bc0f having been created (or likely set to public, and then private).  It then failed to render IIIF Manifests (403 error) and broke the UniversalViewer for DPUL.

**Comment by hackmastera** [comment]
Never reproduced and this functionality was all just worked on. If it happens again we'll reopen or make a new ticket.
