### ISSUE TITLE
Use an authorization token for indexing manifests

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/pomegranate#590]
Auth token will be used to index netid-only, campus-only, and reading room resources.

To support having items that are campus-only.

Current behavior is that they're not indexed.

**Comment by hackmastera** [comment]
@tpendragon Was this addressed at all with the orchestra work?

**Comment by tpendragon** [comment]
Oh. Yeah. This is done.

**Comment by tpendragon** [comment]
Closed by #733
