### ISSUE TITLE
Thumbnails not displaying on search results

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/pomegranate#592]
I think this is a result of https://github.com/pulibrary/pomegranate/blob/master/app/helpers/application_helper.rb#L82

`@document` isn't defined in search results. I pushed up a branch to test, but I can't deploy it because of an existing issue with the `shared_files` mount not being able to mount ATM.

**Comment by kelea99** [comment]
Can we make this a high priority, @tpendragon ? We need it for the exhibit, opening Sept 12, and I just got a rush request for it for the Spain 15M movement from Fernando.
