### ISSUE TITLE
Fix dpul-staging

### ISSUE THREAD

**Issue by escowles** [pulibrary/pomegranate#593]
Currently getting an error because the solr core dpul-staging doesn't exist.

**Comment by hackmastera** [comment]
Ansible thinks it should be on lib-solr https://github.com/pulibrary/princeton_ansible/blob/master/group_vars/dpul_staging.yml#L57-L58

Many other applications are using lib-solr-staging

Checking lib-solr-staging's admin ui, I do see a dpul-staging core. I'm going to try updating the dpul_staging playbook to use lib-solr-staging; seems like that might be enough to fix this.

**Comment by hackmastera** [comment]
It seems like that worked to some extent; you can now click on collections, etc. But they don't have any content. The solr index has 13357 results for a blank query, though.
