### ISSUE TITLE
Recent Items Widget

### ISSUE THREAD

**Issue by escowles** [pulibrary/pomegranate#597]
LAE has a "recent items" display — other ephemera projects would like to have a similar widget that shows the most recently-added items.

**Comment by tpendragon** [comment]
Current WIP:
![Screen Shot 2019-09-19 at 5 08 02 PM](https://user-images.githubusercontent.com/2806645/65289573-16c4f400-db00-11e9-96e5-e825937c0364.png)

**Comment by tpendragon** [comment]
One issue with this is right now I'm just sorting by the Solr timestamp, so it's less "recently added" and more "recently indexed." I don't think DPUL gets the Figgy created date or anything (and I actually think this is how LAE works but I'm not positive), so if we want to do that we'd have to adjust.

**Comment by escowles** [comment]
That screenshot looks great — and adding the Figgy object timestamps for other models the way we do for Ephemera sounds like a good way to be able to figure out what's been recently added.
