### ISSUE TITLE
Custom Fields Should Be Able To Be Links

### ISSUE THREAD

**Issue by escowles** [pulibrary/pomegranate#598]
e.g., for ephemera, many fields are using controlled vocabularies, and making links to canned searches.

**Comment by tpendragon** [comment]
Strategy:

Spotlight::CustomFields should be able to have the option `include_in_search: true` set in its config via some sort of checkbox or something in the UI.

The primary question I have is: where should the checkbox be?

**Comment by escowles** [comment]
Probably in Dashboard > Curation > Metadata Display — though that table is already very large and wide, so I'm not sure how easy it will be to add the checkbox there.  Is there a detail view of the imported metadata fields where the checkbox could go?

**Comment by tpendragon** [comment]
There is, but they're hidden for read only fields. We could add them back, it'll look pretty gnarly.

Looking at how we'd probably have to implement this I think I'd like to wait until we upgrade Spotlight though, since it looks like we'd have to override some views.
