### ISSUE TITLE
Add CSV Downloads to Bookmarks

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/pomegranate#613]
Similar functionality exists in Orangelight, added in https://github.com/pulibrary/orangelight/pull/1491.

**Comment by hackmastera** [comment]
We're not sure whether to export the default metadata outside the context of any exhibit (you'd never get custom fields, e.g.) or the metadata in the context of the exhibit from which it was bookmarked (headers would have to be a superset of fields included in each exhibit for which any item was boomarked). A clear use case would help guide the direction of this feature.

**Comment by hackmastera** [comment]
Use case came from someone who originally wanted OCR content, and revised the request to ask for several metadata fields.

Initial fields to include are title, creator, date, subject, coverage, location, language.

**Comment by hackmastera** [comment]
@escowles what is coverage? Isn't that a map thing?

**Comment by escowles** [comment]
Sorry, I should have said "Geo subject" — "coverage" is what DC calls the place a resource is about, as opposed to the place where it's from.
