### ISSUE TITLE
Bookmarks should lead to the item in the context of the collection they were bookmarked from

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/pomegranate#614]

**Comment by hackmastera** [comment]
Currently if I bookmark the same object from different collections, my bookmark link says I have 2 bookmarks, but when I go to my bookmarks page it only says / shows 1. I believe repository retrieval deduplicates based on the manifest url. This is probably desirable in the general search results screen, but maybe not in bookmarks? If what we care about is exhibit-specific metadata?
