### ISSUE TITLE
How to remove "Item Visibility" facet from collection?

### ISSUE THREAD

**Issue by hackmastera** [pulibrary/pomegranate#632]
There is not an option for it in dashboard > search > facets. It's showing up on the sidebar for the `sae` collection in dpul-staging. https://dpul-staging.princeton.edu/sae. Reported by @kelea99.

**Comment by tpendragon** [comment]
You can't remove it, but it's an administrative facet. If only shows up for logged in curators. Maybe there's some way we can make it clearer they don't have to worry about it.

**Comment by kelea99** [comment]
Cool. Thanks, @hackmastera and @tpendragon. We will make sure to explain it to people as well when we meet with everyone on Monday.
