### ISSUE TITLE
Reindexing an exhibit should appropriately mark things private/public

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/pomegranate#635]
Right now this logic is locked up in the FiggyEventProcessor, so only happens in response to RabbitMQ events.

Code:
https://github.com/pulibrary/pomegranate/blob/master/app/services/figgy_event_processor/update_processor.rb#L24-L32

We should try removing this out of there and putting it in the Reindex job.

**Comment by hackmastera** [comment]
Currently affecting @tventimi on https://dpul.princeton.edu/eastasian/catalog
