### ISSUE TITLE
"Recent Additions" Widget only displaying 9 out of 10 items. Can we Display all 10?

### ISSUE THREAD

**Issue by kelea99** [pulibrary/pomegranate#636]
not sure if this is a bug (perhaps the lurking bug number 2 for the private items?) or a parameter that can be reset to display all 10 items?  
![Screen Shot 2019-10-04 at 12 01 47 PM (3)](https://user-images.githubusercontent.com/45043014/66222346-f4ee7400-e69e-11e9-96d0-7cc3a15803e6.png)

**Comment by hackmastera** [comment]
I think maybe it's noticeable because the collection only has 10 items. The recent items widget has to stop at some threshold. Did you want that to be 10 in general? Whatever we set it at will be for the whole site. Maybe @tpendragon can speak to why he chose 9. Looks like lae shows 8.

**Comment by hackmastera** [comment]
8 might be good actually, since they're 4 across. Seems possible you'd have a run of items with the same dimensions.

**Comment by tpendragon** [comment]
I have no good reason for 9, I just thought an uneven number would look neat
