### ISSUE TITLE
Can we add "Geographic Subject" to Facet options? 

### ISSUE THREAD

**Issue by kelea99** [pulibrary/pomegranate#637]
We cannot find geo subject in the facet options in DPUL staging for the ephemera.  can this be added as a facet option? Thanks!
![Screen Shot 2019-10-04 at 12 14 14 PM (3)](https://user-images.githubusercontent.com/45043014/66223038-81e5fd00-e6a0-11e9-8c79-d6a67cc86137.png)

**Comment by kelea99** [comment]
@tpendragon and @hackmastera, would it be possible to get it added by Monday? not essential, but would be nice to have.

**Comment by tpendragon** [comment]
This field is in here, but named "Coverage" instead, which is confusing. Created https://github.com/pulibrary/figgy/issues/3414 to fix that, and closing this.
