### ISSUE TITLE
Bookmarks/CSV in DPUL staging?

### ISSUE THREAD

**Issue by kelea99** [pulibrary/pomegranate#640]
@tpendragon @hackmastera, I know y'all were working on this for DPUL.  Any chance to have it in staging for the meeting? If not, it might be good to be ready to discuss it this afternoon?

**Comment by tpendragon** [comment]
@kelea99 It should be there already.

**Comment by kelea99** [comment]
@tpendragon huh. lemme look again. I may have missed it. Oh! maybe I can only see it if we publish the site in staging versus edit mode?
