### ISSUE TITLE
Remove Arial Unicode MS from font faces

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/pomegranate#662]
It breaks connecting characters.

This isn't a massive priority, but must be done before SAE goes live.

**Comment by hackmastera** [comment]
It's an option also in the header and footer. It's okay there?

**Comment by tpendragon** [comment]
Yes, as long as only Latin script shows up there.

**Comment by hackmastera** [comment]
Yeah, I couldn't think of a way non-latin script could show up there.
