### ISSUE TITLE
Load spreadsheet of metadata into custom fields

### ISSUE THREAD

**Issue by hackmastera** [pulibrary/pomegranate#672]
[Portraits_ot_Picturesque.xlsx](https://github.com/pulibrary/pomegranate/files/4077586/Portraits_ot_Picturesque.xlsx)

Since simple resources still can't be edited we can't put this metadata into figgy. In addition these items will be cataloged in MARC. At that time the data source will change.

**Comment by kelea99** [comment]
Hold off on merging Medata into fields for Portraits of Picturesque. I found a way to integrate it all without your needing to do anything. Thanks!

**Comment by hackmastera** [comment]
Not needed
