### ISSUE TITLE
broken thumbnail

### ISSUE THREAD

**Issue by hackmastera** [pulibrary/pomegranate#673]
broken thumbnail for: Granada, Distant View of the Sierra Nevada (on listing of all itemss here: https://dpul.princeton.edu/picturesque/browse/the-picturesque-abroad

This exhibit opens Wednesday.

**Comment by hackmastera** [comment]
I reindexed the collection.

The object has the right thumbnail in solr: https://dpul.princeton.edu/picturesque/catalog/bg257m44z.json

**Comment by kelea99** [comment]
it works! Looks great, @hackmastera . thank you!
