### ISSUE TITLE
Unable to email bookmarked items

### ISSUE THREAD

**Issue by escowles** [pulibrary/pomegranate#704]
Reported by Fernando via Snap. Steps to reproduce:
1. Bookmark an item on the search results page
2. View bookmarks and click "Email"
3. Fill out form and submit the form.
4. The error message "Network Error" is displayed.

**Comment by escowles** [comment]
Honeybadger says the error is:
> ArgumentError: SMTP From address may not be blank: nil

https://github.com/mikel/mail/blob/7c43c84c16f017e0ff5e5c9962f6a1d842301ee3//lib/mail/check_delivery_params.rb#L13

https://app.honeybadger.io/projects/51733/faults/59851660 (creating/linking an issue wasn't working for some reason)

**Comment by tpendragon** [comment]
Closed in favor of #705 (which is linked to Honeybadger)
