### ISSUE TITLE
Need to be able to develop a DPUL site while Figgy items are still incomplete

### ISSUE THREAD

**Issue by hackartisan** [pulibrary/pomegranate#707]
The SAE project has used their unpublished DPUL exhibit to demonstrate their project while it is still in development and Figgy items are not yet complete.

There may be ongoing use cases here which would necessitate rethinking https://github.com/pulibrary/pomegranate/issues/684. I'm following up with Ellen.

As a curator I want to build a dpul exhibit before the metadata is complete in figgy so that I can demo it to stakeholders and get feedback.

**Comment by kelea99** [comment]
@hackmastera I believe there will be ongoing use cases.

**Comment by hackmastera** [comment]
In looking for more context on why it initially worked the way it did, I only found https://github.com/pulibrary/pomegranate/issues/83 which shows the initial plan had been to delete them, but in the implementation they were marked private.

In discussion of #684 we noted that the resource should be retained in case it held custom field data. This is why the solr record was deemed safe to remove.

https://github.com/pulibrary/pomegranate/issues/632 is tangentially related but doesn't contain a use case.

All this is to say, it looks like we do need to keep the solr record, after all.

Ellen will be back in mid-February and can discuss then.

**Comment by kelea99** [comment]
We have demoed an unpublished site for ephemera, with completed ephemera items that only display in the unpublished DPUL site for review (since it is not linked to catalog records). Emma was happy with this way forward. Closing ticket.
