### ISSUE TITLE
Unable to index docs with children

### ISSUE THREAD

**Issue by hackmastera** [pulibrary/pomegranate#712]
Is there something about this document that makes solr think it has child documents?

[Pomegranate/staging] IIIFResource::IndexingError: Failed to update Solr for the following documents: 97416f4a38eaa90130eac4cf98faf71d

## Backtrace

    line 97 of [PROJECT_ROOT]/app/models/iiif_resource.rb: rescue in write_to_index
    line 88 of [PROJECT_ROOT]/app/models/iiif_resource.rb: write_to_index
    line 59 of [PROJECT_ROOT]/app/models/iiif_resource.rb: reindex

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/51733/faults/59879245)

**Comment by tpendragon** [comment]
This is usually because some field isn't being converted right and it's trying to index a nested ID field.

**Comment by hackmastera** [comment]
Usually this is a problem with an ephemera field or an id field. resolving #710 will help make this easier to figure out.

**Comment by hackmastera** [comment]
closing. the data is no longer on this hb error, there's nothing in the solr index with that id, and #779 the currently-known instances of this error.
