### ISSUE TITLE
Generate ADR about decision to name things Collection vs Exhibits.

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/pomegranate#720]

**Comment by kelea99** [comment]
Do you need my input/information gathering at all on this, @tpendragon and @hackmastera?

**Comment by hackmastera** [comment]
@kelea99 We're working on some documentation of architectural decisions that were made in the past as a way of externalizing institutional memory. So I don't think we'll need you but I'm happy to @ you on the PR if you'd like to review what we produce. To give you a sense of what these will look like, here are some we did yesterday: https://github.com/pulibrary/pomegranate/pull/722/files

**Comment by kelea99** [comment]
thanks so much, @hackmastera! No need to at all. Im always interested in learning more, so just out of curiosity id love to read it, but certainly don't need to review!
