### ISSUE TITLE
Slavic Collection Rendering Slowly

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/pomegranate#731]
It takes between 20-30 seconds to load right now. Datadog says it's running the query to load the blacklight config 5500 times: https://app.datadoghq.com/apm/resource/pomegranate/rack.request/892147145d819509?end=1581357032543&env=none&event=AQAAAXAwNbY08Tx1xwAAAABBWEF3TmNWQnFIMGhQN0lkamlKRA&graphType=span_list&index=apm-search&isMonitorPanelOpened=false&paused=false&routing_hint=1581356791348&spanID=6211733745141823828&start=1581353432543&traceID=4862303344453850803

**Comment by tpendragon** [comment]
There were roughly 3400 `Spotlight::CustomFields` attached to that exhibit for the `type` field from the JSON-LD, all with the same field but with different slugs. For some reason on import it's not recognizing that those fields already exist, apparently.

For now I just deleted all the dups and it's much faster.

**Comment by tpendragon** [comment]
Selections from Near East Collections has about 6k dups, I'm gonna kill those too.

**Comment by tpendragon** [comment]
Exhibit ID to type dups:
```
[[13, 0], [4, 0], [30, 0], [11, 1], [9, 1], [10, 1], [12, 0], [15, 0], [18, 1], [16, 0], [40, 4], [23, 0], [24, 0], [42, 1], [44, 0], [37, 0], [31, 0], [35, 0], [45, 0], [46, 4], [39, 0], [38, 0], [36, 0], [41, 0], [48, 0], [52, 0], [55, 0], [51, 0]]
```

So things should be much quicker in general now.

**Comment by tpendragon** [comment]
I'm going to go to sleep. I tracked this down to this:

When an item imports it checks to make sure that a given key doesn't already exist as a label for all the fields that exist. The problem is to do that it uses `Spotlight::CustomField#label`, which first checks the blacklight config to see if the user has overridden that label.

The labels are mapped here: https://github.com/projectblacklight/spotlight/blob/master/app/models/spotlight/resources/iiif_manifest.rb#L114

The comparison happens here:
https://github.com/projectblacklight/spotlight/blob/master/app/models/spotlight/resources/iiif_manifest.rb#L109

The problem is on import the key is `@type`, but a user has changed it to `Type` for an existing field. This check should really be making sure the field name doesn't already exist. We should patch that.

IN the meantime, I'm changing those fields for Slavic and Near East Collections back to `@type` as a label to stop proliferation and hiding them from display.

**Comment by tpendragon** [comment]
As a final note, you can check for the proliferating things like this:
```
Spotlight::CustomField.all.select{|v| v.slug.length > 30}.size
```
The slugs get a UUID, so they're real long.

**Comment by hackmastera** [comment]
Working to replicate in development / trying to formulate a test, and so far what I'm seeing varies slightly from this initial report. 

Notes:

* On import the key is `type`, and it's capitalized by the code. 
* This is also happening for other fields.

Able to replicate by creating Figgy's "Shibui Collection"

**Comment by tpendragon** [comment]
It happens for any field that gets renamed by a curator in an exhibit.
