### ISSUE TITLE
I would like to be able to click a "view in catalog" hyperlink for each item within a DPUL collection that will take me to the item record in the online catalog and/or finding aid.

### ISSUE THREAD

**Issue by kelea99** [pulibrary/pomegranate#736]
This was brought up during a training session for DPUL today, and I think it is something worth making a priority. The suggestion was made by Emma Sarconi, who had heard feedback while she was serving on a working group requesting this very thing for online exhibitions in general. Looking at figgy metadata, the source metadata id does link to the cat record. is there a way we could feed that field with the hyperlink into DPUL?

**Comment by kelea99** [comment]
@hackmastera I would like this to also work for the FA (see above) :) thank you!

**Comment by hackmastera** [comment]
This is done except there were some items that didn't reindex; those are ticketed in #779
