### ISSUE TITLE
Font change and all Caps now showing on DPUL masthead/banner and main menu. Overlay also gone.

### ISSUE THREAD

**Issue by kelea99** [pulibrary/pomegranate#746]
Not necessarily a bad thing (I kinda like the fuzzy overlay being nixed), actually, but if it wasn't planned, then worth looking at what happened. Thanks!

![Screen Shot 2020-02-26 at 3 03 08 PM (3)](https://user-images.githubusercontent.com/45043014/75382845-42b38500-58a9-11ea-92bd-fad4bfcc5060.png)

![Screen Shot 2020-02-26 at 3 02 55 PM (3)](https://user-images.githubusercontent.com/45043014/75382854-4810cf80-58a9-11ea-9f52-244622a288c6.png)

**Comment by hackmastera** [comment]
@kelea99 I'm not really sure what it used to look like. do you happen to have any old screenshots on your computer??

I definitely see the vertical alignment issues in the subnav.

**Comment by kelea99** [comment]
Ive got an old screenshot from staging and am looking for another which may prove more useful: 
![Screen Shot 2019-10-03 at 10 35 17 AM (3)](https://user-images.githubusercontent.com/45043014/75386920-7cd45500-58b0-11ea-8879-e3e781b630cd.png)

**Comment by kelea99** [comment]
Additions: the search box isn't lining up properly (thanks, @sdellis ) and the masthead width may be wonky as well?
