### ISSUE TITLE
Allow users with non-princeton email addresses

### ISSUE THREAD

**Issue by hackmastera** [pulibrary/pomegranate#750]
the uid and email should both be the person's full email address.

Similar work in figgy: https://github.com/pulibrary/figgy/pull/3239/files

Once it's deployed to prod the user account in question needs to be fixed up. Roles that use the accounts should be removed and then the accounts should be deleted (it's recreated when the user is added again). There are 2 -- user ids are 126034 and 127463.

**Comment by hackmastera** [comment]
I'm not sure what usage difference is between `uid` and `username`.

**Comment by kelea99** [comment]
@hackmastera, Alas! user cannot access DPUL site at all now. He has given me screenshot if it helps 
![image](https://user-images.githubusercontent.com/45043014/75759527-b9b2a880-5d03-11ea-9106-2eebb1f18f58.png)
