### ISSUE TITLE
Find source of invalid filter

### ISSUE THREAD

**Issue by jrgriffiniii** [pulibrary/pomegranate#762]
How is it possible to get here? https://dpul.princeton.edu/slavic/catalog?f[readonly_collections_ssim]

## Backtrace

    line 6 of [PROJECT_ROOT]/app/views/catalog/index.html.erb: _app_views_catalog_index_html_erb__2328934974460750695_47308346216540

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/51733/faults/61279371)

**Comment by jrgriffiniii** [comment]
Currently the `search_results` partial does not handle certain `nil` values:

```
ActionView::Template::Error: undefined method `size' for nil:NilClass

[PROJECT_ROOT]/app/views/catalog/index.html.erb:6:in `_app_views_catalog_index_html_erb'
4 
5 <div id="content" class="<%= main_content_classes %>">
6   <%= render 'search_results' %>
7 </div>
```

**Comment by hackmastera** [comment]
Members of our team have tried to track this type of error in the past without luck. We don't think this is a link generated by our app.
