### ISSUE TITLE
"Curator" role in Dashboard only gives access to Curation options and no configuration options. Is this what we want to happen?

### ISSUE THREAD

**Issue by kelea99** [pulibrary/pomegranate#766]
More of a question to discuss: do we want DPUL to work this way for curators? Im not sure it is necessary for admin roles to be the only ones that can change thumbnails/collection description/title and subtitles for flippy cards, the main banner, main menu, etc. Thoughts?  What curator role currently has access to in Dashboard: 

Dashboard
Analytics
---------
**Curation**
Items
Tags
Browse
Feature pages
About pages

**Comment by kelea99** [comment]
For the time being, I am giving admin access to a curator for their exhibit, @hackmastera

**Comment by hackmastera** [comment]
Yes, curators should be given admin access for their exhibits without reservation.
