### ISSUE TITLE
Curator picture missing

### ISSUE THREAD

**Issue by hackmastera** [pulibrary/pomegranate#768]
Pages with broken images:
* https://dpul.princeton.edu/islamicmss/about/islamic-manuscript-collections
* https://dpul.princeton.edu/scheide/about/scheide-library
* https://dpul.princeton.edu/cotsen/about/the-cotsen-children-s-library
* https://dpul.princeton.edu/eastasian/about/about

## Backtrace

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/51733/faults/55289472)

**Comment by christinach** [comment]
`image/66/Setsuko.jpg` is also missing. In this case is there a contact email to inform that an image is missing?

**Comment by hackmastera** [comment]
It would probably be good to figure out how we lost them

**Comment by kelea99** [comment]
@christinach and @hackmastera : an idea about curator pictures: many folks had pictures retaken by the digital studio. if the pics were changed, then the image link would be broken, yes?

**Comment by hackmastera** [comment]
Probably these photos were uploaded before we put the shared mount in place.

The images were pulled from the staff directory, and should be replaced.

**Comment by hackmastera** [comment]
@kelea99 will reupload these.

**Comment by kelea99** [comment]
@hackmastera. images re-uploaded and saved in google drive folder:  https://drive.google.com/drive/folders/1TMvQrdxOrDeA0eTpQNCkh86z2veDWHLy
