### ISSUE TITLE
Make Vector resources sync from figgy

### ISSUE THREAD

**Issue by hackmastera** [pulibrary/pomegranate#776]
Folks in SC are going to start  creating smaller DPUL exhibits from various content that  is currently available in figgy. A geo-rectified map is one of the items they would like to include.

related to #777?

**Comment by hackmastera** [comment]
Vector resources don't have manifests so this would be a significant feature request.

@kelea99 Can you give us more background on the exhibit and this request? Is it possible there is a related scanned map that would work as an alternative?

**Comment by kelea99** [comment]
Hi, @hackmastera was able to get one to sync, but the other may be a problem in figgy.  this is the item that Christina and I tested on Friday : https://figgy.princeton.edu/catalog/0aafa01b-7e1f-42de-b093-2a015fe1a039

and this is the one I had no problem with: https://figgy.princeton.edu/catalog/f5f26d2c-c3b7-4a50-98f6-8bd30a7eb623

**Comment by kelea99** [comment]
Exhibit background: this is the first of a new program in SC:  thee Collections are selections of 10 to 15 images already available and publicly visible in Figgy, arranged and described around a theme.

**Comment by hackmastera** [comment]
Spoke with @kelea99. We'll ask curators to look for a way to point back to the maps portal in the text of a related object.
