### ISSUE TITLE
Make default facets

### ISSUE THREAD

**Issue by jpstroop** [pulibrary/pomegranate#78]
Publisher isn't a good one. Let's do subjects (split into topic, geo, temporal/period, names, and genre [example](https://pulsearch.princeton.edu/catalog?utf8=%E2%9C%93&search_field=all_fields&q=)), date, format, and language. @tampakis may be able to help here.

**Comment by tpendragon** [comment]
I don't think there are any default facets now. You define them in the dashboard.

**Comment by jpstroop** [comment]
OK. Is it still possible to do it in the CatalogController (or somewhere else)? Publisher is just a particularly bad default.

**Comment by jpstroop** [comment]
(however it's getting there)

**Comment by tpendragon** [comment]
Are you seeing publisher on a newly added exhibit? I've added it myself in the dashboard as an example. I don't think it's a default now, but I'll take a look

**Comment by jpstroop** [comment]
Oh, OK, that's probably it.
