### ISSUE TITLE
Finding Aids Imported Attributes are not displaying in DPUL

### ISSUE THREAD

**Issue by kelea99** [pulibrary/pomegranate#781]
**example:** 
item in DPUL: https://dpul.princeton.edu/open-country/catalog/4q77fr62j _(I added the photography information in DPUL)_
item in Figgy: https://figgy.princeton.edu/catalog/b627a6ce-6717-4dd0-a16a-7a0c0b8a5788
Item in FA: https://findingaids.princeton.edu/collections/WC064/c932

**Comment by kelea99** [comment]
Hi, @hackmastera ! Gabriel asked me for an update with this. how are things looking?

**Comment by hackmastera** [comment]
Hi @kelea99, this issue will be part of the sprint starting on Monday and appears to be the highest priority right now.

**Comment by kelea99** [comment]
Perfect! just confirming.

**Comment by hackmastera** [comment]
Resolved by the figgy PR.
