### ISSUE TITLE
Can you build a hierarchy in spotlight?

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/pomegranate#8]
Use cases being, e.g. 

 * http://library.princeton.edu/njmaps/
 * http://rbsc.princeton.edu/versailles/versailles-paper

Which are sort of hierarchical, but the real point is that (I) should be able to group things into pages and create links to those pages in an order that (I) choose.

@tpendragon @escowles fair?

**Comment by tpendragon** [comment]
Can do.

**Comment by jpstroop** [comment]
:+1:
