### ISSUE TITLE
I would like the "Performance Ensembles" Collection in Figgy to have a different DPUL slug. 

### ISSUE THREAD

**Issue by kelea99** [pulibrary/pomegranate#808]
Current DPUL slug: https://dpul.princeton.edu/puo

User-Requested DPUL slug: https://dpul.princeton.edu/performances

Reason for change: The Princeton Performance Ensembles collection in figgy has grown to contain more than just the Princeton University Orchestra (PUO), and Dan from Mendel has asked that the URL reflect that. We decided on a more general slug "performances", to cover more accurately what all the collection contains.

**Comment by hackmastera** [comment]
I'm planning to do this on Monday morning during the maintenance window.

**Comment by hackmastera** [comment]
Done.

**Comment by kelea99** [comment]
Wrote to Dan G. to let him know.
