### ISSUE TITLE
Collection image for 'Welcome Additions' does not display

### ISSUE THREAD

**Issue by christinach** [pulibrary/pomegranate#843]
Thomas Keenan reported that the 'Welcome Additions' image does not display on the homepage https://dpul.princeton.edu/.

When checking the developer tools, it fails to resolve https://iiif.princeton.edu/loris/figgy_prod%2F68%2F6a%2F42%2F686a4285778c4a4c880c6226f91944a7%2Fintermediate_file.jp2/25553,5504,13871,13888/400,400/0/default.jpg

**Comment by hackmastera** [comment]
Deleted the thumbnail and re-linked with the resource. @kelea99 please correct if the cropping is off.

**Comment by kelea99** [comment]
Done,  @hackmastera ! thanks. it looks great!
