### ISSUE TITLE
Curated Pages thumbnail selection malfunctioning for some pages in unpublished Shibui Exhibition site

### ISSUE THREAD

**Issue by kelea99** [pulibrary/pomegranate#844]
Submitted by Nicole Fabricand Person.  She is giving a graduate seminar next week on the Shibui collection and DPUL site and she has lost some of the thumbnails for her pages.  Please see the [Collection Thumbnail](https://dpul.princeton.edu/shibui/feature/the-collection-a29c5b64-b1db-45cf-a324-4506d0195b06/edit) as an example. When she goes in to try to rectify it, she cannot. the square selection tool does not appear and the selected item does not appear as the thumbnail.  Can we get this working for her before next week?

Original Correspondence:
_Hi Kim,

I will be giving a presentation to a graduate seminar next week on the Shibui collection/site and I find that I have lost some of the thumbnails--for example, The Collection thumbnail on the home page. When I go in to try to rectify this, I cannot. The square bracket that is to be used to define the part of the image you want as the thumbnail does not appear. This is happening in a number of places and I can't seem to find a solution.

Any help you can offer will be greatly appreciated!_

**Comment by hackmastera** [comment]
This was fixed by deleting the thumbnail in the database and linking it up again. It should be reviewed to ensure it's the desired image.
