### ISSUE TITLE
Collection gives a 404 when the slug has a capital letter

### ISSUE THREAD

**Issue by kelea99** [pulibrary/pomegranate#857]
What I am doing in DPUL (I first created the collections in Figgy, obviously):
1. Create Collection
2. select from the dropdown of the collection options
3. Selected "Khenpo Sodargye Lectures Collection" (I also tried, before this "Khenpo Sodargye Lectures") - screenshot
4. clicked save.
5. i was then directed to a "this page does not exist" dpul page - screenshot
<img width="1440" alt="Screen Shot 2020-12-03 at 8 10 22 AM" src="https://user-images.githubusercontent.com/45043014/101022367-4dd5c880-353f-11eb-80c0-8dc400083db8.png">
<img width="1440" alt="Screen Shot 2020-12-03 at 8 10 47 AM" src="https://user-images.githubusercontent.com/45043014/101022377-50d0b900-353f-11eb-824a-cfdc03ef5c49.png">

**Comment by kelea99** [comment]
additional note:  both unpublished collections do show up in in my listing, it just takes you to the "this page doesn't exist" when you click to enter

**Comment by kelea99** [comment]
I just tried adding and completing a test item to see if that helped. no. still nothing.

**Comment by kelea99** [comment]
update: creating collections works fine for @escowles. Perhaps its my account/permissions? can someone check for me?

**Comment by hackartisan** [comment]
Routing gives a 404 when the slug has a capital letter. I deleted these in the db and @kelea99 changed the slugs in figgy and was able to create the collections in dpul. We should decide whether we want to allow capitals and look at the routing here in dpul, or not allow capitals and validate slugs for all-lowercase in figgy. @kelea99 do you have a preference? I'm changing the title of this issue now that we know what's happening.

**Comment by kelea99** [comment]
I dont believe this is a priority and I dont mind keeping all lowercase for the foreseeable future. I think we do need to document it and inform folks, however. @kelynch , the Mudd and SC colleagues who you spoke with regarding slug creation in figgy--is there documentation or would you like me to make something? Happy to do so! regardless, we should tell them asap.

**Comment by hackartisan** [comment]
@kelea99 Got it, thanks. Even if it's not a priority, though, it seems like it would be good to know which way we want to go. Do you have a preference? I do think it is more conventional for urls to be lowercase so I might lean in that direction.

**Comment by escowles** [comment]
@hackartisan 👍🏻 to requiring the URLs to be lowercase — I think it would be potentially very confusing to have case-sensitive collection slugs.

**Comment by hackartisan** [comment]
👍 closing in favor of figgy#4340

**Comment by kelea99** [comment]
Agree with @escowles . All lower case , it is :)
