### ISSUE TITLE
Cannot make language public in configuration dashboard

### ISSUE THREAD

**Issue by kelea99** [pulibrary/pomegranate#860]
Fernando and I have been working with the options in the Dashboard and have added Spanish as a language for the 
[Colección Archivo Fotográfico de la Protesta en Chile 2019 Exhibit](https://dpul.princeton.edu/chilean_photographs). Fernando has added translations, but when i try to make the language option public, the box unchecks when i click "save". 
![Screen Shot 2020-12-07 at 6 01 38 PM](https://user-images.githubusercontent.com/45043014/101415698-5bc87800-38b6-11eb-84ac-5bad969edddf.png)
![Screen Shot 2020-12-07 at 6 01 27 PM](https://user-images.githubusercontent.com/45043014/101415723-63881c80-38b6-11eb-82de-65d05cae15ef.png)

**Comment by hackartisan** [comment]
To the question "can we easily fix this" the answer is I'm not sure. It's definitely a bug and I was able to reproduce it with a test, but I don't have insight yet on what's causing it.

**Comment by hackartisan** [comment]
@kelynch discovered that we are able to set this value to public manually. Would you like us to do that @kelea99 ?

**Comment by hackartisan** [comment]
Looks like the params aren't permitted

**Comment by hackartisan** [comment]
okay I think I fixed it; PR forthcoming.

**Comment by kelea99** [comment]
hey, i would like that to happen if we can.
