### ISSUE TITLE
Allow being able to attach a note to the exhibit.

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/pomegranate#87]
This should be a private note field for curators/admins. 
> Use cases might be things like "contact curator X when this goes live" or "this is a temporary exhibit corresponding with the gallery exhibit and should be removed on date X"

**Comment by tpendragon** [comment]
@joycebcat Can you expand on this? You want one note on the exhibit you can edit that only admins of the exhibit can see? Multiple notes? Public somehow?

**Comment by joycebcat** [comment]
@tpendragon I think what I had in mind was a private note field that only curators and admins could see.  Use cases might be things like "contact curator X when this goes live" or "this is a temporary exhibit corresponding with the gallery exhibit and should be removed on date X"

**Comment by hackmastera** [comment]
We no longer have this use case
