### ISSUE TITLE
Search Across Implementation

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/pomegranate#91]

**Comment by jpstroop** [comment]
I wonder if Solr's [FieldCollaping / Result Grouping](https://wiki.apache.org/solr/FieldCollapsing) could help us dedupe here. If the NOID from Plum was in Pom's Solr, we could group by it, I think?

**Comment by escowles** [comment]
We could probably use the manifest URI for this instead of the NOID.

**Comment by jpstroop** [comment]
Yeah, good point.
